import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, Plus, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileDropzone } from "@/components/file-dropzone";
import { uploadToBucket, signBucketPath, removeFromBucket } from "@/lib/storage-upload";
import { DOCUMENTO_ESTADOS, SUBVENCION_HITOS, TAREA_ESTADOS, TAREA_PRIORIDADES } from "@/lib/subvenciones";
import { Money } from "@/components/money";

const db = supabase as any;
const peopleQuery = async () => { const { data, error } = await db.from("people").select("id, full_name").eq("role", "ic_team").order("full_name"); if (error) throw error; return data ?? []; };

function Remove({ onClick }: { onClick: () => void }) { return <Button variant="ghost" size="sm" onClick={onClick} aria-label="Eliminar" title="Eliminar"><Trash2 className="h-4 w-4"/></Button>; }
function PersonSelect({ value, onChange, people }: { value?: string | null; onChange:(v:string|null)=>void; people:any[] }) { return <Select value={value || "none"} onValueChange={v=>onChange(v==="none"?null:v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sin asignar</SelectItem>{people.map(p=><SelectItem key={p.id} value={p.id}>{p.full_name}</SelectItem>)}</SelectContent></Select>; }

export function GrantBudgetEditor({ grantId, grantName }: { grantId:string; grantName:string }) {
  const qc=useQueryClient(); const key=["subvencion-partidas",grantId];
  const q=useQuery({queryKey:key,queryFn:async()=>{const {data,error}=await db.from("subvencion_partidas").select("*").eq("subvencion_id",grantId).order("created_at");if(error)throw error;return data??[];}});
  const [form,setForm]=useState<any>({concepto:"",categoria:"",proveedor:"",presupuesto_previsto:"",gasto_elegible:"",porcentaje_financiable:"",general_budget_category:"gasto_otros",general_budget_year:String(new Date().getFullYear()),general_budget_month:String(new Date().getMonth()+1)});
  async function add(){if(!form.concepto.trim())return toast.error("Indica el concepto.");const pct=Number(form.porcentaje_financiable)||0;const eligible=Number(form.gasto_elegible)||0;const {error}=await db.from("subvencion_partidas").insert({...form,subvencion_id:grantId,presupuesto_previsto:Number(form.presupuesto_previsto)||0,gasto_elegible:eligible,porcentaje_financiable:pct,subvencion_imputable:eligible*pct/100,aportacion_propia:Math.max(0,eligible-eligible*pct/100),general_budget_year:Number(form.general_budget_year),general_budget_month:Number(form.general_budget_month)});if(error)return toast.error(error.message);setForm({...form,concepto:"",categoria:"",proveedor:"",presupuesto_previsto:"",gasto_elegible:"",porcentaje_financiable:""});qc.invalidateQueries({queryKey:key});}
  async function send(row:any){if(row.sent_to_general_budget_at)return;const {data,error}=await db.from("ic_budget_lines").insert({year:row.general_budget_year,month:row.general_budget_month,category:row.general_budget_category,amount:row.presupuesto_previsto,notes:`Subvención · ${grantName} · ${row.concepto}`,source_grant_id:grantId,source_grant_line_id:row.id}).select("id").single();if(error)return toast.error(error.message);await db.from("subvencion_partidas").update({sent_to_general_budget_at:new Date().toISOString(),general_budget_line_id:data.id}).eq("id",row.id);toast.success("Partida enviada al presupuesto general");qc.invalidateQueries({queryKey:key});qc.invalidateQueries({queryKey:["ic-budget"]});}
  async function remove(row:any){if(row.general_budget_line_id)await db.from("ic_budget_lines").delete().eq("id",row.general_budget_line_id);await db.from("subvencion_partidas").delete().eq("id",row.id);qc.invalidateQueries({queryKey:key});}
  return <div className="space-y-4"><div className="grid gap-3 border-y border-border py-4 lg:grid-cols-6"><Field label="Concepto"><Input value={form.concepto} onChange={e=>setForm({...form,concepto:e.target.value})}/></Field><Field label="Categoría"><Input value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})}/></Field><Field label="Proveedor"><Input value={form.proveedor} onChange={e=>setForm({...form,proveedor:e.target.value})}/></Field><Field label="Presupuesto"><Input type="number" value={form.presupuesto_previsto} onChange={e=>setForm({...form,presupuesto_previsto:e.target.value})}/></Field><Field label="Elegible"><Input type="number" value={form.gasto_elegible} onChange={e=>setForm({...form,gasto_elegible:e.target.value})}/></Field><Field label="% ayuda"><Input type="number" value={form.porcentaje_financiable} onChange={e=>setForm({...form,porcentaje_financiable:e.target.value})}/></Field><Field label="Año"><Input type="number" value={form.general_budget_year} onChange={e=>setForm({...form,general_budget_year:e.target.value})}/></Field><Field label="Mes"><Input type="number" min="1" max="12" value={form.general_budget_month} onChange={e=>setForm({...form,general_budget_month:e.target.value})}/></Field><Field label="Partida general"><Select value={form.general_budget_category} onValueChange={v=>setForm({...form,general_budget_category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="gasto_personal">Personal</SelectItem><SelectItem value="gasto_operativo">Operativo</SelectItem><SelectItem value="gasto_marketing">Marketing</SelectItem><SelectItem value="gasto_otros">Otros</SelectItem></SelectContent></Select></Field><div className="flex items-end lg:col-span-3"><Button onClick={add}><Plus className="mr-2 h-4 w-4"/>Añadir partida</Button></div></div>
  <div className="overflow-x-auto"><table className="w-full text-base"><thead><tr className="text-left smallcaps text-xs text-muted-foreground"><th className="py-2">Partida</th><th>Presupuesto</th><th>Elegible</th><th>Ayuda</th><th>Aportación</th><th>Presupuesto general</th><th/></tr></thead><tbody className="divide-y divide-border">{(q.data??[]).map((r:any)=><tr key={r.id}><td className="py-3"><strong>{r.concepto}</strong><span className="block text-sm text-muted-foreground">{[r.categoria,r.proveedor].filter(Boolean).join(" · ")}</span></td><td><Money value={r.presupuesto_previsto}/></td><td><Money value={r.gasto_elegible}/></td><td><Money value={r.subvencion_imputable}/><span className="block text-sm">{r.porcentaje_financiable??0}%</span></td><td><Money value={r.aportacion_propia}/></td><td>{r.sent_to_general_budget_at?<span className="text-success">Enviada</span>:<Button variant="outline" size="sm" onClick={()=>send(r)}><Send className="mr-1 h-4 w-4"/>Enviar</Button>}</td><td><Remove onClick={()=>remove(r)}/></td></tr>)}</tbody></table></div></div>;
}

export function GrantMilestonesEditor({grantId}:{grantId:string}){
  const qc=useQueryClient(),key=["subvencion-hitos",grantId];const q=useQuery({queryKey:key,queryFn:async()=>{const {data,error}=await db.from("subvencion_hitos").select("*, responsable:people(full_name)").eq("subvencion_id",grantId).order("fecha_interna");if(error)throw error;return data??[];}});const pq=useQuery({queryKey:["people-grants"],queryFn:peopleQuery});const [f,setF]=useState<any>({nombre:"Solicitud",fecha_oficial:"",fecha_interna:"",responsable_person_id:"",estado:"Pendiente",alerta_dias:"7"});
  async function add(){const {error}=await db.from("subvencion_hitos").insert({...f,subvencion_id:grantId,fecha_oficial:f.fecha_oficial||null,fecha_interna:f.fecha_interna||null,responsable_person_id:f.responsable_person_id||null,alerta_dias:f.alerta_dias?Number(f.alerta_dias):null});if(error)return toast.error(error.message);qc.invalidateQueries({queryKey:key});}
  async function remove(id:string){await db.from("subvencion_hitos").delete().eq("id",id);qc.invalidateQueries({queryKey:key});}
  return <><div className="grid gap-3 border-y border-border py-4 md:grid-cols-6"><Field label="Hito"><Select value={f.nombre} onValueChange={v=>setF({...f,nombre:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{SUBVENCION_HITOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Fecha oficial"><Input type="date" value={f.fecha_oficial} onChange={e=>setF({...f,fecha_oficial:e.target.value})}/></Field><Field label="Fecha interna"><Input type="date" value={f.fecha_interna} onChange={e=>setF({...f,fecha_interna:e.target.value})}/></Field><Field label="Responsable"><PersonSelect value={f.responsable_person_id} onChange={v=>setF({...f,responsable_person_id:v??""})} people={pq.data??[]}/></Field><Field label="Alerta (días)"><Input type="number" value={f.alerta_dias} onChange={e=>setF({...f,alerta_dias:e.target.value})}/></Field><div className="flex items-end"><Button onClick={add}><Plus className="mr-1 h-4 w-4"/>Añadir</Button></div></div><Rows rows={q.data??[]} columns={(r:any)=><><td className="py-3 font-semibold">{r.nombre}</td><td>{r.fecha_oficial||"—"}</td><td>{r.fecha_interna||"—"}</td><td>{r.responsable?.full_name||"—"}</td><td>{r.estado}</td><td><Remove onClick={()=>remove(r.id)}/></td></>}/></>;
}

export function GrantDocumentsEditor({grantId}:{grantId:string}){
  const qc=useQueryClient(),key=["subvencion-documentos",grantId];const q=useQuery({queryKey:key,queryFn:async()=>{const{data,error}=await db.from("subvencion_documentos").select("*, responsable:people(full_name)").eq("subvencion_id",grantId).order("created_at");if(error)throw error;return data??[];}});const pq=useQuery({queryKey:["people-grants"],queryFn:peopleQuery});const[f,setF]=useState<any>({nombre:"",obligatorio:false,responsable_person_id:"",proporcionado_por:"",estado:"Pendiente",requiere_firma:false,firmante:"",fecha_limite_interna:"",fecha_limite_oficial:"",observaciones:""});
  async function add(){if(!f.nombre.trim())return toast.error("Indica el documento.");const{error}=await db.from("subvencion_documentos").insert({...f,subvencion_id:grantId,responsable_person_id:f.responsable_person_id||null,fecha_limite_interna:f.fecha_limite_interna||null,fecha_limite_oficial:f.fecha_limite_oficial||null});if(error)return toast.error(error.message);setF({...f,nombre:""});qc.invalidateQueries({queryKey:key});}
  async function upload(row:any,files:File[]){try{const file=files[0];if(!file)return;const path=await uploadToBucket("grant-documents",`${grantId}/${row.id}`,file);if(row.archivo_path)await removeFromBucket("grant-documents",row.archivo_path);await db.from("subvencion_documentos").update({archivo_path:path}).eq("id",row.id);qc.invalidateQueries({queryKey:key});toast.success("Documento subido");}catch(e:any){toast.error(e.message);}}
  async function open(path:string){const url=await signBucketPath("grant-documents",path,300);if(url)window.open(url,"_blank");}
  async function remove(row:any){await removeFromBucket("grant-documents",row.archivo_path);await db.from("subvencion_documentos").delete().eq("id",row.id);qc.invalidateQueries({queryKey:key});}
  return <><div className="grid gap-3 border-y border-border py-4 md:grid-cols-4"><Field label="Documento"><Input value={f.nombre} onChange={e=>setF({...f,nombre:e.target.value})}/></Field><Field label="Responsable"><PersonSelect value={f.responsable_person_id} onChange={v=>setF({...f,responsable_person_id:v??""})} people={pq.data??[]}/></Field><Field label="Quién lo proporciona"><Input value={f.proporcionado_por} onChange={e=>setF({...f,proporcionado_por:e.target.value})}/></Field><Field label="Estado"><Select value={f.estado} onValueChange={v=>setF({...f,estado:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{DOCUMENTO_ESTADOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Fecha interna"><Input type="date" value={f.fecha_limite_interna} onChange={e=>setF({...f,fecha_limite_interna:e.target.value})}/></Field><Field label="Fecha oficial"><Input type="date" value={f.fecha_limite_oficial} onChange={e=>setF({...f,fecha_limite_oficial:e.target.value})}/></Field><Field label="Firmante"><Input value={f.firmante} onChange={e=>setF({...f,firmante:e.target.value})}/></Field><div className="flex items-end gap-5"><label className="flex items-center gap-2"><Checkbox checked={f.obligatorio} onCheckedChange={v=>setF({...f,obligatorio:!!v})}/>Obligatorio</label><label className="flex items-center gap-2"><Checkbox checked={f.requiere_firma} onCheckedChange={v=>setF({...f,requiere_firma:!!v})}/>Firma</label></div><div className="md:col-span-4"><Button onClick={add}><Plus className="mr-1 h-4 w-4"/>Añadir documento</Button></div></div>
  <div className="divide-y divide-border">{(q.data??[]).map((r:any)=><div key={r.id} className="grid items-center gap-3 py-4 md:grid-cols-[1.5fr,1fr,1fr,1fr,auto]"><div><strong>{r.nombre}</strong><span className="block text-sm text-muted-foreground">{r.obligatorio?"Obligatorio":"Opcional"}{r.requiere_firma?` · Firma: ${r.firmante||"pendiente"}`:""}</span></div><span>{r.responsable?.full_name||"—"}</span><span>{r.estado}</span><div>{r.archivo_path?<Button variant="outline" size="sm" onClick={()=>open(r.archivo_path)}><FileText className="mr-1 h-4 w-4"/>Abrir</Button>:<FileDropzone multiple={false} onFiles={files=>upload(r,files)} className="py-2" label="Subir archivo"/>}</div><Remove onClick={()=>remove(r)}/></div>)}</div></>;
}

export function GrantTasksEditor({grantId}:{grantId:string}){
  const qc=useQueryClient(),key=["subvencion-tareas",grantId];const q=useQuery({queryKey:key,queryFn:async()=>{const{data,error}=await db.from("subvencion_tareas").select("*, responsable:people(full_name), documento:subvencion_documentos(nombre), dependencia:subvencion_tareas!subvencion_tareas_dependencia_id_fkey(titulo)").eq("subvencion_id",grantId).order("fecha_limite");if(error)throw error;return data??[];}});const pq=useQuery({queryKey:["people-grants"],queryFn:peopleQuery});const dq=useQuery({queryKey:["subvencion-documentos",grantId],queryFn:async()=>{const{data}=await db.from("subvencion_documentos").select("id,nombre").eq("subvencion_id",grantId);return data??[];}});const[f,setF]=useState<any>({titulo:"",responsable_person_id:"",fecha_limite:"",dependencia_id:"",estado:"Pendiente",documento_id:"",prioridad:"Media"});
  async function add(){if(!f.titulo.trim())return toast.error("Indica la tarea.");const{data,error}=await db.from("actions").insert({subject_type:"grant",subject_id:grantId,title:f.titulo,due_date:f.fecha_limite||null,kind:"tarea",assignee_person_id:f.responsable_person_id||null,area:"legal",subarea:"subvencion"}).select("id").single();if(error)return toast.error(error.message);const{error:e2}=await db.from("subvencion_tareas").insert({...f,subvencion_id:grantId,responsable_person_id:f.responsable_person_id||null,fecha_limite:f.fecha_limite||null,dependencia_id:f.dependencia_id||null,documento_id:f.documento_id||null,action_id:data.id});if(e2)return toast.error(e2.message);setF({...f,titulo:"",dependencia_id:"",documento_id:""});qc.invalidateQueries({queryKey:key});}
  async function remove(r:any){if(r.action_id)await db.from("actions").delete().eq("id",r.action_id);await db.from("subvencion_tareas").delete().eq("id",r.id);qc.invalidateQueries({queryKey:key});}
  return <><div className="grid gap-3 border-y border-border py-4 md:grid-cols-4"><Field label="Tarea"><Input value={f.titulo} onChange={e=>setF({...f,titulo:e.target.value})}/></Field><Field label="Responsable"><PersonSelect value={f.responsable_person_id} onChange={v=>setF({...f,responsable_person_id:v??""})} people={pq.data??[]}/></Field><Field label="Fecha límite"><Input type="date" value={f.fecha_limite} onChange={e=>setF({...f,fecha_limite:e.target.value})}/></Field><Field label="Prioridad"><Select value={f.prioridad} onValueChange={v=>setF({...f,prioridad:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TAREA_PRIORIDADES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Estado"><Select value={f.estado} onValueChange={v=>setF({...f,estado:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TAREA_ESTADOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Depende de"><Select value={f.dependencia_id||"none"} onValueChange={v=>setF({...f,dependencia_id:v==="none"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sin dependencia</SelectItem>{(q.data??[]).map((x:any)=><SelectItem key={x.id} value={x.id}>{x.titulo}</SelectItem>)}</SelectContent></Select></Field><Field label="Documento asociado"><Select value={f.documento_id||"none"} onValueChange={v=>setF({...f,documento_id:v==="none"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sin documento</SelectItem>{(dq.data??[]).map((x:any)=><SelectItem key={x.id} value={x.id}>{x.nombre}</SelectItem>)}</SelectContent></Select></Field><div className="flex items-end"><Button onClick={add}><Plus className="mr-1 h-4 w-4"/>Añadir</Button></div></div><Rows rows={q.data??[]} columns={(r:any)=><><td className="py-3 font-semibold">{r.titulo}</td><td>{r.responsable?.full_name||"—"}</td><td>{r.fecha_limite||"—"}</td><td>{r.prioridad} · {r.estado}</td><td>{r.dependencia?.titulo||r.documento?.nombre||"—"}</td><td><Remove onClick={()=>remove(r)}/></td></>}/></>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label className="mb-1.5 block text-xs">{label}</Label>{children}</div>}
function Rows({rows,columns}:{rows:any[];columns:(r:any)=>React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full text-base"><tbody className="divide-y divide-border">{rows.map(r=><tr key={r.id}>{columns(r)}</tr>)}</tbody></table></div>}