import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { SaveButton } from "@/components/save-button";
import { ConfirmDeleteButton } from "@/components/confirm-delete-button";
import { ListSkeleton } from "@/components/list-states";
import { GrantBudgetEditor, GrantDocumentsEditor, GrantMilestonesEditor, GrantTasksEditor } from "@/components/grant-section-editors";
import { SUBVENCION_ESTADOS, SUBVENCION_TIPOS } from "@/lib/subvenciones";

const db = supabase as any;
export const Route = createFileRoute("/_authenticated/_admin/oportunidades/subvenciones/$subvencionId")({
  component: GrantDetailPage,
  head: () => ({ meta: [
    { title: "Ficha de subvención | Interesante Compañía" },
    { name: "description", content: "Expediente completo de subvención, presupuesto, hitos, documentos y justificación." },
    { property: "og:title", content: "Ficha de subvención | Interesante Compañía" },
    { property: "og:description", content: "Expediente completo de subvención, presupuesto, hitos, documentos y justificación." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
  ] }),
});

const SECTIONS = ["Identificación", "Economía y tesorería", "Presupuesto", "Calendario", "Documentación", "Presentación", "Tareas", "Datos presentados", "Resolución y cobro", "Justificación"];

function GrantDetailPage(){
  const {subvencionId}=Route.useParams();const navigate=useNavigate();const qc=useQueryClient();const[form,setForm]=useState<any>(null);const[saving,setSaving]=useState(false);
  const q=useQuery({queryKey:["subvencion",subvencionId],queryFn:async()=>{const{data,error}=await db.from("oportunidades_subvenciones").select("*").eq("id",subvencionId).maybeSingle();if(error)throw error;return data;}});
  const peopleQ=useQuery({queryKey:["people-grants"],queryFn:async()=>{const{data,error}=await db.from("people").select("id,full_name").eq("role","ic_team").order("full_name");if(error)throw error;return data??[];}});
  const versionQ=useQuery({queryKey:["subvencion-versiones",subvencionId],queryFn:async()=>{const{data,error}=await db.from("subvencion_versiones_presentacion").select("*").eq("subvencion_id",subvencionId).order("version",{ascending:false});if(error)throw error;return data??[];}});
  useEffect(()=>{if(q.data)setForm({...q.data});},[q.data]);
  if(q.isLoading||!form)return <div className="mx-auto max-w-[1700px] p-8"><ListSkeleton rows={8}/></div>;
  const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
  async function save(){setSaving(true);const payload={...form};delete payload.id;delete payload.created_at;delete payload.updated_at;for(const k of Object.keys(payload))if(payload[k]==="")payload[k]=null;const{error}=await db.from("oportunidades_subvenciones").update(payload).eq("id",subvencionId);setSaving(false);if(error)return toast.error(error.message);toast.success("Expediente guardado");qc.invalidateQueries({queryKey:["subvencion",subvencionId]});qc.invalidateQueries({queryKey:["subvenciones"]});qc.invalidateQueries({queryKey:["subvencion-versiones",subvencionId]});}
  async function remove(){const{error}=await db.from("oportunidades_subvenciones").delete().eq("id",subvencionId);if(error)return toast.error(error.message);navigate({to:"/oportunidades/subvenciones"});}
  return <div className="mx-auto max-w-[1700px] px-6 py-8">
    <div className="sticky top-0 z-20 -mx-6 mb-8 border-b border-border bg-background/95 px-6 py-4 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><Button asChild variant="ghost" size="icon" title="Volver"><Link to="/oportunidades/subvenciones"><ArrowLeft className="h-5 w-5"/></Link></Button><div><p className="smallcaps text-rust">Subvención · {form.estado}</p><h1 className="font-display text-4xl font-extrabold">{form.nombre_corto||form.nombre_convocatoria}</h1></div></div><div className="flex items-center gap-2">{form.url_convocatoria&&<Button asChild variant="outline"><a href={form.url_convocatoria} target="_blank" rel="noreferrer"><ExternalLink className="mr-2 h-4 w-4"/>Convocatoria</a></Button>}<ConfirmDeleteButton onConfirm={remove} title="¿Eliminar esta subvención?"/><SaveButton onClick={save} saving={saving} floating/></div></div><nav className="mt-4 flex gap-4 overflow-x-auto pb-1 text-sm font-semibold">{SECTIONS.map((s,i)=><a key={s} href={`#bloque-${i+1}`} className="whitespace-nowrap text-muted-foreground hover:text-primary">{i+1}. {s}</a>)}</nav></div>
    <div className="space-y-12">
      <Section id="bloque-1" n="01" title="Identificación"><Grid><Field label="Nombre corto"><Input value={form.nombre_corto??""} onChange={e=>set("nombre_corto",e.target.value)}/></Field><Field label="Nombre oficial" wide><Input value={form.nombre_convocatoria??""} onChange={e=>set("nombre_convocatoria",e.target.value)}/></Field><Field label="Organismo"><Input value={form.institucion_nombre??""} onChange={e=>set("institucion_nombre",e.target.value)}/></Field><Field label="Empresa solicitante"><Input value={form.empresa_solicitante??""} onChange={e=>set("empresa_solicitante",e.target.value)}/></Field><Field label="Proyecto / área"><Input value={form.proyecto_vinculado??""} onChange={e=>set("proyecto_vinculado",e.target.value)}/></Field><Field label="Tipo de ayuda"><Select value={form.tipo??"Subvención"} onValueChange={v=>set("tipo",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{SUBVENCION_TIPOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Estado"><Select value={form.estado??"Por preparar"} onValueChange={v=>set("estado",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{SUBVENCION_ESTADOS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Responsable"><Select value={form.responsable_person_id||"none"} onValueChange={v=>set("responsable_person_id",v==="none"?null:v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sin asignar</SelectItem>{(peopleQ.data??[]).map((p:any)=><SelectItem key={p.id} value={p.id}>{p.full_name}</SelectItem>)}</SelectContent></Select></Field><Field label="URL oficial" wide><Input value={form.url_convocatoria??""} onChange={e=>set("url_convocatoria",e.target.value)}/></Field></Grid></Section>
      <Section id="bloque-2" n="02" title="Economía y tesorería"><Grid><Num label="Importe máximo" k="importe_maximo" f={form} set={set}/><Num label="% subvencionable" k="porcentaje_subvencionable" f={form} set={set}/><Num label="Importe solicitado" k="importe_solicitado" f={form} set={set}/><Num label="Importe concedido" k="importe_concedido" f={form} set={set}/><Num label="Coste total proyecto" k="coste_total_proyecto" f={form} set={set}/><Num label="Anticipo previsto" k="anticipo_previsto" f={form} set={set}/><Num label="Anticipo cobrado" k="anticipo_cobrado" f={form} set={set}/><Num label="Pendiente de cobro" k="pendiente_cobro" f={form} set={set}/><DateF label="Previsión anticipo" k="fecha_prevision_anticipo" f={form} set={set}/><DateF label="Previsión pago final" k="fecha_prevision_pago_final" f={form} set={set}/></Grid></Section>
      <Section id="bloque-3" n="03" title="Presupuesto del proyecto" description="El envío al presupuesto general es manual y queda enlazado al expediente."><GrantBudgetEditor grantId={subvencionId} grantName={form.nombre_corto||form.nombre_convocatoria}/></Section>
      <Section id="bloque-4" n="04" title="Calendario de hitos" description="La fecha interna se incorpora al calendario general de la agencia."><GrantMilestonesEditor grantId={subvencionId}/></Section>
      <Section id="bloque-5" n="05" title="Documentación"><GrantDocumentsEditor grantId={subvencionId}/></Section>
      <Section id="bloque-6" n="06" title="Instrucciones de presentación"><Grid><Text label="Canal de presentación" k="canal_presentacion" f={form} set={set}/><Text label="Portal de presentación" k="portal_presentacion" f={form} set={set}/><Text label="Usuario / certificado" k="usuario_certificado" f={form} set={set}/><Text label="Firmante requerido" k="firmante_requerido" f={form} set={set}/><Field label="Formatos y límites" wide><Textarea rows={4} value={form.formatos_limites??""} onChange={e=>set("formatos_limites",e.target.value)}/></Field><Field label="Instrucciones internas" wide><Textarea rows={5} value={form.instrucciones_internas??""} onChange={e=>set("instrucciones_internas",e.target.value)}/></Field></Grid></Section>
      <Section id="bloque-7" n="07" title="Tareas y dependencias"><GrantTasksEditor grantId={subvencionId}/></Section>
      <Section id="bloque-8" n="08" title="Datos de presentación" description="Al cambiar el estado a Presentada se conserva automáticamente una versión inmutable."><Grid><DateF label="Fecha de presentación" k="fecha_presentacion" f={form} set={set}/><Text label="Número de expediente" k="numero_expediente" f={form} set={set}/><Text label="Registro de entrada" k="registro_entrada" f={form} set={set}/><Field label="Justificante de presentación" wide><Input value={form.justificante_presentacion_path??""} onChange={e=>set("justificante_presentacion_path",e.target.value)}/></Field></Grid>{(versionQ.data??[]).length>0&&<div className="mt-5 border-t border-border pt-4"><h3 className="font-display text-xl font-semibold">Versiones presentadas</h3><div className="mt-2 flex flex-wrap gap-2">{versionQ.data.map((v:any)=><span key={v.id} className="border border-border px-3 py-2 text-sm">Versión {v.version} · {new Date(v.presentada_at).toLocaleString("es-ES")}</span>)}</div></div>}</Section>
      <Section id="bloque-9" n="09" title="Resolución y cobro"><Grid><DateF label="Fecha de resolución" k="fecha_resolucion" f={form} set={set}/><Text label="Resultado" k="resultado_resolucion" f={form} set={set}/><Num label="Importe concedido" k="importe_concedido" f={form} set={set}/><Num label="Importe cobrado" k="importe_cobrado" f={form} set={set}/><DateF label="Fecha de cobro" k="fecha_cobro" f={form} set={set}/><Field label="Condiciones de resolución" wide><Textarea rows={4} value={form.condiciones_resolucion??""} onChange={e=>set("condiciones_resolucion",e.target.value)}/></Field></Grid></Section>
      <Section id="bloque-10" n="10" title="Justificación"><Grid><DateF label="Fecha límite" k="fecha_limite_justificacion" f={form} set={set}/><DateF label="Fecha presentada" k="fecha_presentacion_justificacion" f={form} set={set}/><Num label="Importe justificado" k="importe_justificado" f={form} set={set}/><Num label="Importe aceptado" k="importe_aceptado_justificacion" f={form} set={set}/><Text label="Estado" k="estado_justificacion" f={form} set={set}/><Field label="Observaciones" wide><Textarea rows={5} value={form.observaciones_justificacion??""} onChange={e=>set("observaciones_justificacion",e.target.value)}/></Field></Grid></Section>
    </div>
  </div>;
}

function Section({id,n,title,description,children}:{id:string;n:string;title:string;description?:string;children:React.ReactNode}){return <section id={id} className="scroll-mt-36 border-t-4 border-primary pt-5"><div className="mb-6 flex items-start gap-4"><span className="font-mono text-xl font-bold text-rust">{n}</span><div><h2 className="font-display text-3xl font-bold">{title}</h2>{description&&<p className="mt-1 text-muted-foreground">{description}</p>}</div></div>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{children}</div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={wide?"xl:col-span-2":""}><Label className="mb-2 block">{label}</Label>{children}</div>}
function Text({label,k,f,set}:{label:string;k:string;f:any;set:(k:string,v:any)=>void}){return <Field label={label}><Input value={f[k]??""} onChange={e=>set(k,e.target.value)}/></Field>}
function Num({label,k,f,set}:{label:string;k:string;f:any;set:(k:string,v:any)=>void}){return <Field label={`${label} (€)`}><Input type="number" value={f[k]??""} onChange={e=>set(k,e.target.value===""?null:Number(e.target.value))}/></Field>}
function DateF({label,k,f,set}:{label:string;k:string;f:any;set:(k:string,v:any)=>void}){return <Field label={label}><Input type="date" value={f[k]??""} onChange={e=>set(k,e.target.value)}/></Field>}