/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalProyectosRouteImport } from './routes/_authenticated/portal/proyectos'
import { Route as AuthenticatedPortalPropuestasRouteImport } from './routes/_authenticated/portal/propuestas'
import { Route as AuthenticatedPortalMensajesRouteImport } from './routes/_authenticated/portal/mensajes'
import { Route as AuthenticatedPortalContratosRouteImport } from './routes/_authenticated/portal/contratos'
import { Route as AuthenticatedPortalCarreraRouteImport } from './routes/_authenticated/portal/carrera'
import { Route as AuthenticatedPortalAgendaRouteImport } from './routes/_authenticated/portal/agenda'
import { Route as AuthenticatedAdminRosterRouteImport } from './routes/_authenticated/_admin/roster'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/_admin/calendar'
import { Route as AuthenticatedAdminBudgetRouteImport } from './routes/_authenticated/_admin/budget'
import { Route as AuthenticatedAdminProductionsIndexRouteImport } from './routes/_authenticated/_admin/productions.index'
import { Route as AuthenticatedAdminProductionCompaniesIndexRouteImport } from './routes/_authenticated/_admin/production-companies.index'
import { Route as AuthenticatedAdminPlatformsIndexRouteImport } from './routes/_authenticated/_admin/platforms.index'
import { Route as AuthenticatedAdminPeopleIndexRouteImport } from './routes/_authenticated/_admin/people.index'
import { Route as AuthenticatedAdminOpportunitiesIndexRouteImport } from './routes/_authenticated/_admin/opportunities.index'
import { Route as AuthenticatedAdminDirectorsIndexRouteImport } from './routes/_authenticated/_admin/directors.index'
import { Route as AuthenticatedAdminContractsIndexRouteImport } from './routes/_authenticated/_admin/contracts.index'
import { Route as AuthenticatedAdminComposersIndexRouteImport } from './routes/_authenticated/_admin/composers.index'
import { Route as AuthenticatedAdminProductionsProductionIdRouteImport } from './routes/_authenticated/_admin/productions.$productionId'
import { Route as AuthenticatedAdminProductionCompaniesCompanyIdRouteImport } from './routes/_authenticated/_admin/production-companies.$companyId'
import { Route as AuthenticatedAdminPeoplePersonIdRouteImport } from './routes/_authenticated/_admin/people.$personId'
import { Route as AuthenticatedAdminOpportunitiesOpportunityIdRouteImport } from './routes/_authenticated/_admin/opportunities.$opportunityId'
import { Route as AuthenticatedAdminDirectorsDirectorIdRouteImport } from './routes/_authenticated/_admin/directors.$directorId'
import { Route as AuthenticatedAdminContractsContractIdRouteImport } from './routes/_authenticated/_admin/contracts.$contractId'
import { Route as AuthenticatedAdminComposersNewRouteImport } from './routes/_authenticated/_admin/composers.new'
import { Route as AuthenticatedAdminComposersComposerIdRouteImport } from './routes/_authenticated/_admin/composers.$composerId'
import { Route as AuthenticatedAdminMarketingTemplatesIndexRouteImport } from './routes/_authenticated/_admin/marketing.templates.index'
import { Route as AuthenticatedAdminMarketingTargetAccountsIndexRouteImport } from './routes/_authenticated/_admin/marketing.target-accounts.index'
import { Route as AuthenticatedAdminMarketingPressKitsIndexRouteImport } from './routes/_authenticated/_admin/marketing.press-kits.index'
import { Route as AuthenticatedAdminMarketingDecksIndexRouteImport } from './routes/_authenticated/_admin/marketing.decks.index'
import { Route as AuthenticatedAdminMarketingClippingsIndexRouteImport } from './routes/_authenticated/_admin/marketing.clippings.index'
import { Route as AuthenticatedAdminMarketingCaseStudiesIndexRouteImport } from './routes/_authenticated/_admin/marketing.case-studies.index'
import { Route as AuthenticatedAdminMarketingBrandIndexRouteImport } from './routes/_authenticated/_admin/marketing.brand.index'
import { Route as AuthenticatedAdminMarketingTargetAccountsAccountIdRouteImport } from './routes/_authenticated/_admin/marketing.target-accounts.$accountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProyectosRoute =
  AuthenticatedPortalProyectosRouteImport.update({
    id: '/proyectos',
    path: '/proyectos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPropuestasRoute =
  AuthenticatedPortalPropuestasRouteImport.update({
    id: '/propuestas',
    path: '/propuestas',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMensajesRoute =
  AuthenticatedPortalMensajesRouteImport.update({
    id: '/mensajes',
    path: '/mensajes',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalContratosRoute =
  AuthenticatedPortalContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCarreraRoute =
  AuthenticatedPortalCarreraRouteImport.update({
    id: '/carrera',
    path: '/carrera',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAgendaRoute =
  AuthenticatedPortalAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminRosterRoute =
  AuthenticatedAdminRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBudgetRoute =
  AuthenticatedAdminBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionsIndexRoute =
  AuthenticatedAdminProductionsIndexRouteImport.update({
    id: '/productions/',
    path: '/productions/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionCompaniesIndexRoute =
  AuthenticatedAdminProductionCompaniesIndexRouteImport.update({
    id: '/production-companies/',
    path: '/production-companies/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformsIndexRoute =
  AuthenticatedAdminPlatformsIndexRouteImport.update({
    id: '/platforms/',
    path: '/platforms/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleIndexRoute =
  AuthenticatedAdminPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesIndexRoute =
  AuthenticatedAdminOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDirectorsIndexRoute =
  AuthenticatedAdminDirectorsIndexRouteImport.update({
    id: '/directors/',
    path: '/directors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsIndexRoute =
  AuthenticatedAdminContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersIndexRoute =
  AuthenticatedAdminComposersIndexRouteImport.update({
    id: '/composers/',
    path: '/composers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionsProductionIdRoute =
  AuthenticatedAdminProductionsProductionIdRouteImport.update({
    id: '/productions/$productionId',
    path: '/productions/$productionId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionCompaniesCompanyIdRoute =
  AuthenticatedAdminProductionCompaniesCompanyIdRouteImport.update({
    id: '/production-companies/$companyId',
    path: '/production-companies/$companyId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeoplePersonIdRoute =
  AuthenticatedAdminPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesOpportunityIdRoute =
  AuthenticatedAdminOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDirectorsDirectorIdRoute =
  AuthenticatedAdminDirectorsDirectorIdRouteImport.update({
    id: '/directors/$directorId',
    path: '/directors/$directorId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContractsContractIdRoute =
  AuthenticatedAdminContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersNewRoute =
  AuthenticatedAdminComposersNewRouteImport.update({
    id: '/composers/new',
    path: '/composers/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersComposerIdRoute =
  AuthenticatedAdminComposersComposerIdRouteImport.update({
    id: '/composers/$composerId',
    path: '/composers/$composerId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingTemplatesIndexRoute =
  AuthenticatedAdminMarketingTemplatesIndexRouteImport.update({
    id: '/marketing/templates/',
    path: '/marketing/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingTargetAccountsIndexRoute =
  AuthenticatedAdminMarketingTargetAccountsIndexRouteImport.update({
    id: '/marketing/target-accounts/',
    path: '/marketing/target-accounts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingPressKitsIndexRoute =
  AuthenticatedAdminMarketingPressKitsIndexRouteImport.update({
    id: '/marketing/press-kits/',
    path: '/marketing/press-kits/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingDecksIndexRoute =
  AuthenticatedAdminMarketingDecksIndexRouteImport.update({
    id: '/marketing/decks/',
    path: '/marketing/decks/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingClippingsIndexRoute =
  AuthenticatedAdminMarketingClippingsIndexRouteImport.update({
    id: '/marketing/clippings/',
    path: '/marketing/clippings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingCaseStudiesIndexRoute =
  AuthenticatedAdminMarketingCaseStudiesIndexRouteImport.update({
    id: '/marketing/case-studies/',
    path: '/marketing/case-studies/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingBrandIndexRoute =
  AuthenticatedAdminMarketingBrandIndexRouteImport.update({
    id: '/marketing/brand/',
    path: '/marketing/brand/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingTargetAccountsAccountIdRoute =
  AuthenticatedAdminMarketingTargetAccountsAccountIdRouteImport.update({
    id: '/marketing/target-accounts/$accountId',
    path: '/marketing/target-accounts/$accountId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/budget': typeof AuthenticatedAdminBudgetRoute
  '/calendar': typeof AuthenticatedAdminCalendarRoute
  '/roster': typeof AuthenticatedAdminRosterRoute
  '/portal/agenda': typeof AuthenticatedPortalAgendaRoute
  '/portal/carrera': typeof AuthenticatedPortalCarreraRoute
  '/portal/contratos': typeof AuthenticatedPortalContratosRoute
  '/portal/mensajes': typeof AuthenticatedPortalMensajesRoute
  '/portal/propuestas': typeof AuthenticatedPortalPropuestasRoute
  '/portal/proyectos': typeof AuthenticatedPortalProyectosRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/directors/$directorId': typeof AuthenticatedAdminDirectorsDirectorIdRoute
  '/opportunities/$opportunityId': typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  '/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/production-companies/$companyId': typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  '/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/composers/': typeof AuthenticatedAdminComposersIndexRoute
  '/contracts/': typeof AuthenticatedAdminContractsIndexRoute
  '/directors/': typeof AuthenticatedAdminDirectorsIndexRoute
  '/opportunities/': typeof AuthenticatedAdminOpportunitiesIndexRoute
  '/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/platforms/': typeof AuthenticatedAdminPlatformsIndexRoute
  '/production-companies/': typeof AuthenticatedAdminProductionCompaniesIndexRoute
  '/productions/': typeof AuthenticatedAdminProductionsIndexRoute
  '/marketing/target-accounts/$accountId': typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  '/marketing/brand/': typeof AuthenticatedAdminMarketingBrandIndexRoute
  '/marketing/case-studies/': typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  '/marketing/clippings/': typeof AuthenticatedAdminMarketingClippingsIndexRoute
  '/marketing/decks/': typeof AuthenticatedAdminMarketingDecksIndexRoute
  '/marketing/press-kits/': typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  '/marketing/target-accounts/': typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  '/marketing/templates/': typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/budget': typeof AuthenticatedAdminBudgetRoute
  '/calendar': typeof AuthenticatedAdminCalendarRoute
  '/roster': typeof AuthenticatedAdminRosterRoute
  '/portal/agenda': typeof AuthenticatedPortalAgendaRoute
  '/portal/carrera': typeof AuthenticatedPortalCarreraRoute
  '/portal/contratos': typeof AuthenticatedPortalContratosRoute
  '/portal/mensajes': typeof AuthenticatedPortalMensajesRoute
  '/portal/propuestas': typeof AuthenticatedPortalPropuestasRoute
  '/portal/proyectos': typeof AuthenticatedPortalProyectosRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/directors/$directorId': typeof AuthenticatedAdminDirectorsDirectorIdRoute
  '/opportunities/$opportunityId': typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  '/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/production-companies/$companyId': typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  '/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/composers': typeof AuthenticatedAdminComposersIndexRoute
  '/contracts': typeof AuthenticatedAdminContractsIndexRoute
  '/directors': typeof AuthenticatedAdminDirectorsIndexRoute
  '/opportunities': typeof AuthenticatedAdminOpportunitiesIndexRoute
  '/people': typeof AuthenticatedAdminPeopleIndexRoute
  '/platforms': typeof AuthenticatedAdminPlatformsIndexRoute
  '/production-companies': typeof AuthenticatedAdminProductionCompaniesIndexRoute
  '/productions': typeof AuthenticatedAdminProductionsIndexRoute
  '/marketing/target-accounts/$accountId': typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  '/marketing/brand': typeof AuthenticatedAdminMarketingBrandIndexRoute
  '/marketing/case-studies': typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  '/marketing/clippings': typeof AuthenticatedAdminMarketingClippingsIndexRoute
  '/marketing/decks': typeof AuthenticatedAdminMarketingDecksIndexRoute
  '/marketing/press-kits': typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  '/marketing/target-accounts': typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  '/marketing/templates': typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/budget': typeof AuthenticatedAdminBudgetRoute
  '/_authenticated/_admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/_admin/roster': typeof AuthenticatedAdminRosterRoute
  '/_authenticated/portal/agenda': typeof AuthenticatedPortalAgendaRoute
  '/_authenticated/portal/carrera': typeof AuthenticatedPortalCarreraRoute
  '/_authenticated/portal/contratos': typeof AuthenticatedPortalContratosRoute
  '/_authenticated/portal/mensajes': typeof AuthenticatedPortalMensajesRoute
  '/_authenticated/portal/propuestas': typeof AuthenticatedPortalPropuestasRoute
  '/_authenticated/portal/proyectos': typeof AuthenticatedPortalProyectosRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/_admin/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/_authenticated/_admin/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/_authenticated/_admin/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/_authenticated/_admin/directors/$directorId': typeof AuthenticatedAdminDirectorsDirectorIdRoute
  '/_authenticated/_admin/opportunities/$opportunityId': typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  '/_authenticated/_admin/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/_authenticated/_admin/production-companies/$companyId': typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  '/_authenticated/_admin/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/_authenticated/_admin/composers/': typeof AuthenticatedAdminComposersIndexRoute
  '/_authenticated/_admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
  '/_authenticated/_admin/directors/': typeof AuthenticatedAdminDirectorsIndexRoute
  '/_authenticated/_admin/opportunities/': typeof AuthenticatedAdminOpportunitiesIndexRoute
  '/_authenticated/_admin/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/_authenticated/_admin/platforms/': typeof AuthenticatedAdminPlatformsIndexRoute
  '/_authenticated/_admin/production-companies/': typeof AuthenticatedAdminProductionCompaniesIndexRoute
  '/_authenticated/_admin/productions/': typeof AuthenticatedAdminProductionsIndexRoute
  '/_authenticated/_admin/marketing/target-accounts/$accountId': typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  '/_authenticated/_admin/marketing/brand/': typeof AuthenticatedAdminMarketingBrandIndexRoute
  '/_authenticated/_admin/marketing/case-studies/': typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  '/_authenticated/_admin/marketing/clippings/': typeof AuthenticatedAdminMarketingClippingsIndexRoute
  '/_authenticated/_admin/marketing/decks/': typeof AuthenticatedAdminMarketingDecksIndexRoute
  '/_authenticated/_admin/marketing/press-kits/': typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  '/_authenticated/_admin/marketing/target-accounts/': typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  '/_authenticated/_admin/marketing/templates/': typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/me'
    | '/portal'
    | '/budget'
    | '/calendar'
    | '/roster'
    | '/portal/agenda'
    | '/portal/carrera'
    | '/portal/contratos'
    | '/portal/mensajes'
    | '/portal/propuestas'
    | '/portal/proyectos'
    | '/portal/'
    | '/composers/$composerId'
    | '/composers/new'
    | '/contracts/$contractId'
    | '/directors/$directorId'
    | '/opportunities/$opportunityId'
    | '/people/$personId'
    | '/production-companies/$companyId'
    | '/productions/$productionId'
    | '/composers/'
    | '/contracts/'
    | '/directors/'
    | '/opportunities/'
    | '/people/'
    | '/platforms/'
    | '/production-companies/'
    | '/productions/'
    | '/marketing/target-accounts/$accountId'
    | '/marketing/brand/'
    | '/marketing/case-studies/'
    | '/marketing/clippings/'
    | '/marketing/decks/'
    | '/marketing/press-kits/'
    | '/marketing/target-accounts/'
    | '/marketing/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/dashboard'
    | '/me'
    | '/budget'
    | '/calendar'
    | '/roster'
    | '/portal/agenda'
    | '/portal/carrera'
    | '/portal/contratos'
    | '/portal/mensajes'
    | '/portal/propuestas'
    | '/portal/proyectos'
    | '/portal'
    | '/composers/$composerId'
    | '/composers/new'
    | '/contracts/$contractId'
    | '/directors/$directorId'
    | '/opportunities/$opportunityId'
    | '/people/$personId'
    | '/production-companies/$companyId'
    | '/productions/$productionId'
    | '/composers'
    | '/contracts'
    | '/directors'
    | '/opportunities'
    | '/people'
    | '/platforms'
    | '/production-companies'
    | '/productions'
    | '/marketing/target-accounts/$accountId'
    | '/marketing/brand'
    | '/marketing/case-studies'
    | '/marketing/clippings'
    | '/marketing/decks'
    | '/marketing/press-kits'
    | '/marketing/target-accounts'
    | '/marketing/templates'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/me'
    | '/_authenticated/portal'
    | '/_authenticated/'
    | '/_authenticated/_admin/budget'
    | '/_authenticated/_admin/calendar'
    | '/_authenticated/_admin/roster'
    | '/_authenticated/portal/agenda'
    | '/_authenticated/portal/carrera'
    | '/_authenticated/portal/contratos'
    | '/_authenticated/portal/mensajes'
    | '/_authenticated/portal/propuestas'
    | '/_authenticated/portal/proyectos'
    | '/_authenticated/portal/'
    | '/_authenticated/_admin/composers/$composerId'
    | '/_authenticated/_admin/composers/new'
    | '/_authenticated/_admin/contracts/$contractId'
    | '/_authenticated/_admin/directors/$directorId'
    | '/_authenticated/_admin/opportunities/$opportunityId'
    | '/_authenticated/_admin/people/$personId'
    | '/_authenticated/_admin/production-companies/$companyId'
    | '/_authenticated/_admin/productions/$productionId'
    | '/_authenticated/_admin/composers/'
    | '/_authenticated/_admin/contracts/'
    | '/_authenticated/_admin/directors/'
    | '/_authenticated/_admin/opportunities/'
    | '/_authenticated/_admin/people/'
    | '/_authenticated/_admin/platforms/'
    | '/_authenticated/_admin/production-companies/'
    | '/_authenticated/_admin/productions/'
    | '/_authenticated/_admin/marketing/target-accounts/$accountId'
    | '/_authenticated/_admin/marketing/brand/'
    | '/_authenticated/_admin/marketing/case-studies/'
    | '/_authenticated/_admin/marketing/clippings/'
    | '/_authenticated/_admin/marketing/decks/'
    | '/_authenticated/_admin/marketing/press-kits/'
    | '/_authenticated/_admin/marketing/target-accounts/'
    | '/_authenticated/_admin/marketing/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/proyectos': {
      id: '/_authenticated/portal/proyectos'
      path: '/proyectos'
      fullPath: '/portal/proyectos'
      preLoaderRoute: typeof AuthenticatedPortalProyectosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/propuestas': {
      id: '/_authenticated/portal/propuestas'
      path: '/propuestas'
      fullPath: '/portal/propuestas'
      preLoaderRoute: typeof AuthenticatedPortalPropuestasRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/mensajes': {
      id: '/_authenticated/portal/mensajes'
      path: '/mensajes'
      fullPath: '/portal/mensajes'
      preLoaderRoute: typeof AuthenticatedPortalMensajesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/contratos': {
      id: '/_authenticated/portal/contratos'
      path: '/contratos'
      fullPath: '/portal/contratos'
      preLoaderRoute: typeof AuthenticatedPortalContratosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/carrera': {
      id: '/_authenticated/portal/carrera'
      path: '/carrera'
      fullPath: '/portal/carrera'
      preLoaderRoute: typeof AuthenticatedPortalCarreraRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/agenda': {
      id: '/_authenticated/portal/agenda'
      path: '/agenda'
      fullPath: '/portal/agenda'
      preLoaderRoute: typeof AuthenticatedPortalAgendaRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_admin/roster': {
      id: '/_authenticated/_admin/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedAdminRosterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/calendar': {
      id: '/_authenticated/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/budget': {
      id: '/_authenticated/_admin/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedAdminBudgetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/productions/': {
      id: '/_authenticated/_admin/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof AuthenticatedAdminProductionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/production-companies/': {
      id: '/_authenticated/_admin/production-companies/'
      path: '/production-companies'
      fullPath: '/production-companies/'
      preLoaderRoute: typeof AuthenticatedAdminProductionCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/platforms/': {
      id: '/_authenticated/_admin/platforms/'
      path: '/platforms'
      fullPath: '/platforms/'
      preLoaderRoute: typeof AuthenticatedAdminPlatformsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/people/': {
      id: '/_authenticated/_admin/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedAdminPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/opportunities/': {
      id: '/_authenticated/_admin/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/directors/': {
      id: '/_authenticated/_admin/directors/'
      path: '/directors'
      fullPath: '/directors/'
      preLoaderRoute: typeof AuthenticatedAdminDirectorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/contracts/': {
      id: '/_authenticated/_admin/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedAdminContractsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/': {
      id: '/_authenticated/_admin/composers/'
      path: '/composers'
      fullPath: '/composers/'
      preLoaderRoute: typeof AuthenticatedAdminComposersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/productions/$productionId': {
      id: '/_authenticated/_admin/productions/$productionId'
      path: '/productions/$productionId'
      fullPath: '/productions/$productionId'
      preLoaderRoute: typeof AuthenticatedAdminProductionsProductionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/production-companies/$companyId': {
      id: '/_authenticated/_admin/production-companies/$companyId'
      path: '/production-companies/$companyId'
      fullPath: '/production-companies/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminProductionCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/people/$personId': {
      id: '/_authenticated/_admin/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedAdminPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/opportunities/$opportunityId': {
      id: '/_authenticated/_admin/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/directors/$directorId': {
      id: '/_authenticated/_admin/directors/$directorId'
      path: '/directors/$directorId'
      fullPath: '/directors/$directorId'
      preLoaderRoute: typeof AuthenticatedAdminDirectorsDirectorIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/contracts/$contractId': {
      id: '/_authenticated/_admin/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedAdminContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/new': {
      id: '/_authenticated/_admin/composers/new'
      path: '/composers/new'
      fullPath: '/composers/new'
      preLoaderRoute: typeof AuthenticatedAdminComposersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/$composerId': {
      id: '/_authenticated/_admin/composers/$composerId'
      path: '/composers/$composerId'
      fullPath: '/composers/$composerId'
      preLoaderRoute: typeof AuthenticatedAdminComposersComposerIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/templates/': {
      id: '/_authenticated/_admin/marketing/templates/'
      path: '/marketing/templates'
      fullPath: '/marketing/templates/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/target-accounts/': {
      id: '/_authenticated/_admin/marketing/target-accounts/'
      path: '/marketing/target-accounts'
      fullPath: '/marketing/target-accounts/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingTargetAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/press-kits/': {
      id: '/_authenticated/_admin/marketing/press-kits/'
      path: '/marketing/press-kits'
      fullPath: '/marketing/press-kits/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingPressKitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/decks/': {
      id: '/_authenticated/_admin/marketing/decks/'
      path: '/marketing/decks'
      fullPath: '/marketing/decks/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingDecksIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/clippings/': {
      id: '/_authenticated/_admin/marketing/clippings/'
      path: '/marketing/clippings'
      fullPath: '/marketing/clippings/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingClippingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/case-studies/': {
      id: '/_authenticated/_admin/marketing/case-studies/'
      path: '/marketing/case-studies'
      fullPath: '/marketing/case-studies/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingCaseStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/brand/': {
      id: '/_authenticated/_admin/marketing/brand/'
      path: '/marketing/brand'
      fullPath: '/marketing/brand/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingBrandIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/target-accounts/$accountId': {
      id: '/_authenticated/_admin/marketing/target-accounts/$accountId'
      path: '/marketing/target-accounts/$accountId'
      fullPath: '/marketing/target-accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBudgetRoute: typeof AuthenticatedAdminBudgetRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminRosterRoute: typeof AuthenticatedAdminRosterRoute
  AuthenticatedAdminComposersComposerIdRoute: typeof AuthenticatedAdminComposersComposerIdRoute
  AuthenticatedAdminComposersNewRoute: typeof AuthenticatedAdminComposersNewRoute
  AuthenticatedAdminContractsContractIdRoute: typeof AuthenticatedAdminContractsContractIdRoute
  AuthenticatedAdminDirectorsDirectorIdRoute: typeof AuthenticatedAdminDirectorsDirectorIdRoute
  AuthenticatedAdminOpportunitiesOpportunityIdRoute: typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  AuthenticatedAdminPeoplePersonIdRoute: typeof AuthenticatedAdminPeoplePersonIdRoute
  AuthenticatedAdminProductionCompaniesCompanyIdRoute: typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  AuthenticatedAdminProductionsProductionIdRoute: typeof AuthenticatedAdminProductionsProductionIdRoute
  AuthenticatedAdminComposersIndexRoute: typeof AuthenticatedAdminComposersIndexRoute
  AuthenticatedAdminContractsIndexRoute: typeof AuthenticatedAdminContractsIndexRoute
  AuthenticatedAdminDirectorsIndexRoute: typeof AuthenticatedAdminDirectorsIndexRoute
  AuthenticatedAdminOpportunitiesIndexRoute: typeof AuthenticatedAdminOpportunitiesIndexRoute
  AuthenticatedAdminPeopleIndexRoute: typeof AuthenticatedAdminPeopleIndexRoute
  AuthenticatedAdminPlatformsIndexRoute: typeof AuthenticatedAdminPlatformsIndexRoute
  AuthenticatedAdminProductionCompaniesIndexRoute: typeof AuthenticatedAdminProductionCompaniesIndexRoute
  AuthenticatedAdminProductionsIndexRoute: typeof AuthenticatedAdminProductionsIndexRoute
  AuthenticatedAdminMarketingTargetAccountsAccountIdRoute: typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  AuthenticatedAdminMarketingBrandIndexRoute: typeof AuthenticatedAdminMarketingBrandIndexRoute
  AuthenticatedAdminMarketingCaseStudiesIndexRoute: typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  AuthenticatedAdminMarketingClippingsIndexRoute: typeof AuthenticatedAdminMarketingClippingsIndexRoute
  AuthenticatedAdminMarketingDecksIndexRoute: typeof AuthenticatedAdminMarketingDecksIndexRoute
  AuthenticatedAdminMarketingPressKitsIndexRoute: typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  AuthenticatedAdminMarketingTargetAccountsIndexRoute: typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  AuthenticatedAdminMarketingTemplatesIndexRoute: typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBudgetRoute: AuthenticatedAdminBudgetRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminRosterRoute: AuthenticatedAdminRosterRoute,
  AuthenticatedAdminComposersComposerIdRoute:
    AuthenticatedAdminComposersComposerIdRoute,
  AuthenticatedAdminComposersNewRoute: AuthenticatedAdminComposersNewRoute,
  AuthenticatedAdminContractsContractIdRoute:
    AuthenticatedAdminContractsContractIdRoute,
  AuthenticatedAdminDirectorsDirectorIdRoute:
    AuthenticatedAdminDirectorsDirectorIdRoute,
  AuthenticatedAdminOpportunitiesOpportunityIdRoute:
    AuthenticatedAdminOpportunitiesOpportunityIdRoute,
  AuthenticatedAdminPeoplePersonIdRoute: AuthenticatedAdminPeoplePersonIdRoute,
  AuthenticatedAdminProductionCompaniesCompanyIdRoute:
    AuthenticatedAdminProductionCompaniesCompanyIdRoute,
  AuthenticatedAdminProductionsProductionIdRoute:
    AuthenticatedAdminProductionsProductionIdRoute,
  AuthenticatedAdminComposersIndexRoute: AuthenticatedAdminComposersIndexRoute,
  AuthenticatedAdminContractsIndexRoute: AuthenticatedAdminContractsIndexRoute,
  AuthenticatedAdminDirectorsIndexRoute: AuthenticatedAdminDirectorsIndexRoute,
  AuthenticatedAdminOpportunitiesIndexRoute:
    AuthenticatedAdminOpportunitiesIndexRoute,
  AuthenticatedAdminPeopleIndexRoute: AuthenticatedAdminPeopleIndexRoute,
  AuthenticatedAdminPlatformsIndexRoute: AuthenticatedAdminPlatformsIndexRoute,
  AuthenticatedAdminProductionCompaniesIndexRoute:
    AuthenticatedAdminProductionCompaniesIndexRoute,
  AuthenticatedAdminProductionsIndexRoute:
    AuthenticatedAdminProductionsIndexRoute,
  AuthenticatedAdminMarketingTargetAccountsAccountIdRoute:
    AuthenticatedAdminMarketingTargetAccountsAccountIdRoute,
  AuthenticatedAdminMarketingBrandIndexRoute:
    AuthenticatedAdminMarketingBrandIndexRoute,
  AuthenticatedAdminMarketingCaseStudiesIndexRoute:
    AuthenticatedAdminMarketingCaseStudiesIndexRoute,
  AuthenticatedAdminMarketingClippingsIndexRoute:
    AuthenticatedAdminMarketingClippingsIndexRoute,
  AuthenticatedAdminMarketingDecksIndexRoute:
    AuthenticatedAdminMarketingDecksIndexRoute,
  AuthenticatedAdminMarketingPressKitsIndexRoute:
    AuthenticatedAdminMarketingPressKitsIndexRoute,
  AuthenticatedAdminMarketingTargetAccountsIndexRoute:
    AuthenticatedAdminMarketingTargetAccountsIndexRoute,
  AuthenticatedAdminMarketingTemplatesIndexRoute:
    AuthenticatedAdminMarketingTemplatesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAgendaRoute: typeof AuthenticatedPortalAgendaRoute
  AuthenticatedPortalCarreraRoute: typeof AuthenticatedPortalCarreraRoute
  AuthenticatedPortalContratosRoute: typeof AuthenticatedPortalContratosRoute
  AuthenticatedPortalMensajesRoute: typeof AuthenticatedPortalMensajesRoute
  AuthenticatedPortalPropuestasRoute: typeof AuthenticatedPortalPropuestasRoute
  AuthenticatedPortalProyectosRoute: typeof AuthenticatedPortalProyectosRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAgendaRoute: AuthenticatedPortalAgendaRoute,
  AuthenticatedPortalCarreraRoute: AuthenticatedPortalCarreraRoute,
  AuthenticatedPortalContratosRoute: AuthenticatedPortalContratosRoute,
  AuthenticatedPortalMensajesRoute: AuthenticatedPortalMensajesRoute,
  AuthenticatedPortalPropuestasRoute: AuthenticatedPortalPropuestasRoute,
  AuthenticatedPortalProyectosRoute: AuthenticatedPortalProyectosRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
