/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AprobarTokenRouteImport } from './routes/aprobar.$token'
import { Route as AuthenticatedVistaRouteImport } from './routes/_authenticated/vista'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalProyectosRouteImport } from './routes/_authenticated/portal/proyectos'
import { Route as AuthenticatedPortalPropuestasRouteImport } from './routes/_authenticated/portal/propuestas'
import { Route as AuthenticatedPortalPrensaRouteImport } from './routes/_authenticated/portal/prensa'
import { Route as AuthenticatedPortalMensajesRouteImport } from './routes/_authenticated/portal/mensajes'
import { Route as AuthenticatedPortalKpisRouteImport } from './routes/_authenticated/portal/kpis'
import { Route as AuthenticatedPortalFacturacionRouteImport } from './routes/_authenticated/portal/facturacion'
import { Route as AuthenticatedPortalContratosRouteImport } from './routes/_authenticated/portal/contratos'
import { Route as AuthenticatedPortalChatRouteImport } from './routes/_authenticated/portal/chat'
import { Route as AuthenticatedPortalCarreraRouteImport } from './routes/_authenticated/portal/carrera'
import { Route as AuthenticatedPortalAgendaRouteImport } from './routes/_authenticated/portal/agenda'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedAdminTareasRouteImport } from './routes/_authenticated/_admin/tareas'
import { Route as AuthenticatedAdminRosterRouteImport } from './routes/_authenticated/_admin/roster'
import { Route as AuthenticatedAdminIcRouteImport } from './routes/_authenticated/_admin/ic'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/_admin/finance'
import { Route as AuthenticatedAdminDealMemosRouteImport } from './routes/_authenticated/_admin/deal-memos'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/_admin/calendar'
import { Route as AuthenticatedAdminBudgetRouteImport } from './routes/_authenticated/_admin/budget'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/_admin/billing'
import { Route as AuthenticatedAdminAgentActionsRouteImport } from './routes/_authenticated/_admin/agent-actions'
import { Route as AuthenticatedAdminProvidersIndexRouteImport } from './routes/_authenticated/_admin/providers.index'
import { Route as AuthenticatedAdminProductionsIndexRouteImport } from './routes/_authenticated/_admin/productions.index'
import { Route as AuthenticatedAdminProductionCompaniesIndexRouteImport } from './routes/_authenticated/_admin/production-companies.index'
import { Route as AuthenticatedAdminPlatformsIndexRouteImport } from './routes/_authenticated/_admin/platforms.index'
import { Route as AuthenticatedAdminPeopleIndexRouteImport } from './routes/_authenticated/_admin/people.index'
import { Route as AuthenticatedAdminPeliculasEsIndexRouteImport } from './routes/_authenticated/_admin/peliculas-es.index'
import { Route as AuthenticatedAdminOpportunitiesIndexRouteImport } from './routes/_authenticated/_admin/opportunities.index'
import { Route as AuthenticatedAdminDirectorsIndexRouteImport } from './routes/_authenticated/_admin/directors.index'
import { Route as AuthenticatedAdminDealMemosIndexRouteImport } from './routes/_authenticated/_admin/deal-memos.index'
import { Route as AuthenticatedAdminContractsIndexRouteImport } from './routes/_authenticated/_admin/contracts.index'
import { Route as AuthenticatedAdminComposersIndexRouteImport } from './routes/_authenticated/_admin/composers.index'
import { Route as AuthenticatedAdminProductionsProductionIdRouteImport } from './routes/_authenticated/_admin/productions.$productionId'
import { Route as AuthenticatedAdminProductionCompaniesCompanyIdRouteImport } from './routes/_authenticated/_admin/production-companies.$companyId'
import { Route as AuthenticatedAdminPeoplePersonIdRouteImport } from './routes/_authenticated/_admin/people.$personId'
import { Route as AuthenticatedAdminOpportunitiesOpportunityIdRouteImport } from './routes/_authenticated/_admin/opportunities.$opportunityId'
import { Route as AuthenticatedAdminMarketingCalendarRouteImport } from './routes/_authenticated/_admin/marketing.calendar'
import { Route as AuthenticatedAdminDirectorsDirectorIdRouteImport } from './routes/_authenticated/_admin/directors.$directorId'
import { Route as AuthenticatedAdminDealMemosListaRouteImport } from './routes/_authenticated/_admin/deal-memos.lista'
import { Route as AuthenticatedAdminDealMemosConfiguracionRouteImport } from './routes/_authenticated/_admin/deal-memos.configuracion'
import { Route as AuthenticatedAdminDealMemosDealMemoIdRouteImport } from './routes/_authenticated/_admin/deal-memos.$dealMemoId'
import { Route as AuthenticatedAdminContractsContractIdRouteImport } from './routes/_authenticated/_admin/contracts.$contractId'
import { Route as AuthenticatedAdminComposersNewRouteImport } from './routes/_authenticated/_admin/composers.new'
import { Route as AuthenticatedAdminComposersComposerIdRouteImport } from './routes/_authenticated/_admin/composers.$composerId'
import { Route as AuthenticatedAdminMarketingTemplatesIndexRouteImport } from './routes/_authenticated/_admin/marketing.templates.index'
import { Route as AuthenticatedAdminMarketingTargetAccountsIndexRouteImport } from './routes/_authenticated/_admin/marketing.target-accounts.index'
import { Route as AuthenticatedAdminMarketingSocialIndexRouteImport } from './routes/_authenticated/_admin/marketing.social.index'
import { Route as AuthenticatedAdminMarketingPressKitsIndexRouteImport } from './routes/_authenticated/_admin/marketing.press-kits.index'
import { Route as AuthenticatedAdminMarketingDecksIndexRouteImport } from './routes/_authenticated/_admin/marketing.decks.index'
import { Route as AuthenticatedAdminMarketingClippingsIndexRouteImport } from './routes/_authenticated/_admin/marketing.clippings.index'
import { Route as AuthenticatedAdminMarketingCaseStudiesIndexRouteImport } from './routes/_authenticated/_admin/marketing.case-studies.index'
import { Route as AuthenticatedAdminMarketingBrandIndexRouteImport } from './routes/_authenticated/_admin/marketing.brand.index'
import { Route as AuthenticatedAdminDealMemosPlantillasIndexRouteImport } from './routes/_authenticated/_admin/deal-memos.plantillas.index'
import { Route as AuthenticatedAdminMarketingTargetAccountsAccountIdRouteImport } from './routes/_authenticated/_admin/marketing.target-accounts.$accountId'
import { Route as AuthenticatedAdminDealMemosPlantillasPlantillaIdRouteImport } from './routes/_authenticated/_admin/deal-memos.plantillas.$plantillaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AprobarTokenRoute = AprobarTokenRouteImport.update({
  id: '/aprobar/$token',
  path: '/aprobar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVistaRoute = AuthenticatedVistaRouteImport.update({
  id: '/vista',
  path: '/vista',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProyectosRoute =
  AuthenticatedPortalProyectosRouteImport.update({
    id: '/proyectos',
    path: '/proyectos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPropuestasRoute =
  AuthenticatedPortalPropuestasRouteImport.update({
    id: '/propuestas',
    path: '/propuestas',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPrensaRoute =
  AuthenticatedPortalPrensaRouteImport.update({
    id: '/prensa',
    path: '/prensa',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMensajesRoute =
  AuthenticatedPortalMensajesRouteImport.update({
    id: '/mensajes',
    path: '/mensajes',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalKpisRoute = AuthenticatedPortalKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalFacturacionRoute =
  AuthenticatedPortalFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalContratosRoute =
  AuthenticatedPortalContratosRouteImport.update({
    id: '/contratos',
    path: '/contratos',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalChatRoute = AuthenticatedPortalChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalCarreraRoute =
  AuthenticatedPortalCarreraRouteImport.update({
    id: '/carrera',
    path: '/carrera',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAgendaRoute =
  AuthenticatedPortalAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTareasRoute =
  AuthenticatedAdminTareasRouteImport.update({
    id: '/tareas',
    path: '/tareas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRosterRoute =
  AuthenticatedAdminRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIcRoute = AuthenticatedAdminIcRouteImport.update({
  id: '/ic',
  path: '/ic',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealMemosRoute =
  AuthenticatedAdminDealMemosRouteImport.update({
    id: '/deal-memos',
    path: '/deal-memos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBudgetRoute =
  AuthenticatedAdminBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgentActionsRoute =
  AuthenticatedAdminAgentActionsRouteImport.update({
    id: '/agent-actions',
    path: '/agent-actions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProvidersIndexRoute =
  AuthenticatedAdminProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionsIndexRoute =
  AuthenticatedAdminProductionsIndexRouteImport.update({
    id: '/productions/',
    path: '/productions/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionCompaniesIndexRoute =
  AuthenticatedAdminProductionCompaniesIndexRouteImport.update({
    id: '/production-companies/',
    path: '/production-companies/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformsIndexRoute =
  AuthenticatedAdminPlatformsIndexRouteImport.update({
    id: '/platforms/',
    path: '/platforms/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleIndexRoute =
  AuthenticatedAdminPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeliculasEsIndexRoute =
  AuthenticatedAdminPeliculasEsIndexRouteImport.update({
    id: '/peliculas-es/',
    path: '/peliculas-es/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesIndexRoute =
  AuthenticatedAdminOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDirectorsIndexRoute =
  AuthenticatedAdminDirectorsIndexRouteImport.update({
    id: '/directors/',
    path: '/directors/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealMemosIndexRoute =
  AuthenticatedAdminDealMemosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminDealMemosRoute,
  } as any)
const AuthenticatedAdminContractsIndexRoute =
  AuthenticatedAdminContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersIndexRoute =
  AuthenticatedAdminComposersIndexRouteImport.update({
    id: '/composers/',
    path: '/composers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionsProductionIdRoute =
  AuthenticatedAdminProductionsProductionIdRouteImport.update({
    id: '/productions/$productionId',
    path: '/productions/$productionId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionCompaniesCompanyIdRoute =
  AuthenticatedAdminProductionCompaniesCompanyIdRouteImport.update({
    id: '/production-companies/$companyId',
    path: '/production-companies/$companyId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeoplePersonIdRoute =
  AuthenticatedAdminPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOpportunitiesOpportunityIdRoute =
  AuthenticatedAdminOpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingCalendarRoute =
  AuthenticatedAdminMarketingCalendarRouteImport.update({
    id: '/marketing/calendar',
    path: '/marketing/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDirectorsDirectorIdRoute =
  AuthenticatedAdminDirectorsDirectorIdRouteImport.update({
    id: '/directors/$directorId',
    path: '/directors/$directorId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealMemosListaRoute =
  AuthenticatedAdminDealMemosListaRouteImport.update({
    id: '/lista',
    path: '/lista',
    getParentRoute: () => AuthenticatedAdminDealMemosRoute,
  } as any)
const AuthenticatedAdminDealMemosConfiguracionRoute =
  AuthenticatedAdminDealMemosConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedAdminDealMemosRoute,
  } as any)
const AuthenticatedAdminDealMemosDealMemoIdRoute =
  AuthenticatedAdminDealMemosDealMemoIdRouteImport.update({
    id: '/$dealMemoId',
    path: '/$dealMemoId',
    getParentRoute: () => AuthenticatedAdminDealMemosRoute,
  } as any)
const AuthenticatedAdminContractsContractIdRoute =
  AuthenticatedAdminContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersNewRoute =
  AuthenticatedAdminComposersNewRouteImport.update({
    id: '/composers/new',
    path: '/composers/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersComposerIdRoute =
  AuthenticatedAdminComposersComposerIdRouteImport.update({
    id: '/composers/$composerId',
    path: '/composers/$composerId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingTemplatesIndexRoute =
  AuthenticatedAdminMarketingTemplatesIndexRouteImport.update({
    id: '/marketing/templates/',
    path: '/marketing/templates/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingTargetAccountsIndexRoute =
  AuthenticatedAdminMarketingTargetAccountsIndexRouteImport.update({
    id: '/marketing/target-accounts/',
    path: '/marketing/target-accounts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingSocialIndexRoute =
  AuthenticatedAdminMarketingSocialIndexRouteImport.update({
    id: '/marketing/social/',
    path: '/marketing/social/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingPressKitsIndexRoute =
  AuthenticatedAdminMarketingPressKitsIndexRouteImport.update({
    id: '/marketing/press-kits/',
    path: '/marketing/press-kits/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingDecksIndexRoute =
  AuthenticatedAdminMarketingDecksIndexRouteImport.update({
    id: '/marketing/decks/',
    path: '/marketing/decks/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingClippingsIndexRoute =
  AuthenticatedAdminMarketingClippingsIndexRouteImport.update({
    id: '/marketing/clippings/',
    path: '/marketing/clippings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingCaseStudiesIndexRoute =
  AuthenticatedAdminMarketingCaseStudiesIndexRouteImport.update({
    id: '/marketing/case-studies/',
    path: '/marketing/case-studies/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingBrandIndexRoute =
  AuthenticatedAdminMarketingBrandIndexRouteImport.update({
    id: '/marketing/brand/',
    path: '/marketing/brand/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealMemosPlantillasIndexRoute =
  AuthenticatedAdminDealMemosPlantillasIndexRouteImport.update({
    id: '/plantillas/',
    path: '/plantillas/',
    getParentRoute: () => AuthenticatedAdminDealMemosRoute,
  } as any)
const AuthenticatedAdminMarketingTargetAccountsAccountIdRoute =
  AuthenticatedAdminMarketingTargetAccountsAccountIdRouteImport.update({
    id: '/marketing/target-accounts/$accountId',
    path: '/marketing/target-accounts/$accountId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute =
  AuthenticatedAdminDealMemosPlantillasPlantillaIdRouteImport.update({
    id: '/plantillas/$plantillaId',
    path: '/plantillas/$plantillaId',
    getParentRoute: () => AuthenticatedAdminDealMemosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/vista': typeof AuthenticatedVistaRoute
  '/aprobar/$token': typeof AprobarTokenRoute
  '/agent-actions': typeof AuthenticatedAdminAgentActionsRoute
  '/billing': typeof AuthenticatedAdminBillingRoute
  '/budget': typeof AuthenticatedAdminBudgetRoute
  '/calendar': typeof AuthenticatedAdminCalendarRoute
  '/deal-memos': typeof AuthenticatedAdminDealMemosRouteWithChildren
  '/finance': typeof AuthenticatedAdminFinanceRoute
  '/ic': typeof AuthenticatedAdminIcRoute
  '/roster': typeof AuthenticatedAdminRosterRoute
  '/tareas': typeof AuthenticatedAdminTareasRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/portal/agenda': typeof AuthenticatedPortalAgendaRoute
  '/portal/carrera': typeof AuthenticatedPortalCarreraRoute
  '/portal/chat': typeof AuthenticatedPortalChatRoute
  '/portal/contratos': typeof AuthenticatedPortalContratosRoute
  '/portal/facturacion': typeof AuthenticatedPortalFacturacionRoute
  '/portal/kpis': typeof AuthenticatedPortalKpisRoute
  '/portal/mensajes': typeof AuthenticatedPortalMensajesRoute
  '/portal/prensa': typeof AuthenticatedPortalPrensaRoute
  '/portal/propuestas': typeof AuthenticatedPortalPropuestasRoute
  '/portal/proyectos': typeof AuthenticatedPortalProyectosRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/deal-memos/$dealMemoId': typeof AuthenticatedAdminDealMemosDealMemoIdRoute
  '/deal-memos/configuracion': typeof AuthenticatedAdminDealMemosConfiguracionRoute
  '/deal-memos/lista': typeof AuthenticatedAdminDealMemosListaRoute
  '/directors/$directorId': typeof AuthenticatedAdminDirectorsDirectorIdRoute
  '/marketing/calendar': typeof AuthenticatedAdminMarketingCalendarRoute
  '/opportunities/$opportunityId': typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  '/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/production-companies/$companyId': typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  '/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/composers/': typeof AuthenticatedAdminComposersIndexRoute
  '/contracts/': typeof AuthenticatedAdminContractsIndexRoute
  '/deal-memos/': typeof AuthenticatedAdminDealMemosIndexRoute
  '/directors/': typeof AuthenticatedAdminDirectorsIndexRoute
  '/opportunities/': typeof AuthenticatedAdminOpportunitiesIndexRoute
  '/peliculas-es/': typeof AuthenticatedAdminPeliculasEsIndexRoute
  '/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/platforms/': typeof AuthenticatedAdminPlatformsIndexRoute
  '/production-companies/': typeof AuthenticatedAdminProductionCompaniesIndexRoute
  '/productions/': typeof AuthenticatedAdminProductionsIndexRoute
  '/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/deal-memos/plantillas/$plantillaId': typeof AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute
  '/marketing/target-accounts/$accountId': typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  '/deal-memos/plantillas/': typeof AuthenticatedAdminDealMemosPlantillasIndexRoute
  '/marketing/brand/': typeof AuthenticatedAdminMarketingBrandIndexRoute
  '/marketing/case-studies/': typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  '/marketing/clippings/': typeof AuthenticatedAdminMarketingClippingsIndexRoute
  '/marketing/decks/': typeof AuthenticatedAdminMarketingDecksIndexRoute
  '/marketing/press-kits/': typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  '/marketing/social/': typeof AuthenticatedAdminMarketingSocialIndexRoute
  '/marketing/target-accounts/': typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  '/marketing/templates/': typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/vista': typeof AuthenticatedVistaRoute
  '/aprobar/$token': typeof AprobarTokenRoute
  '/agent-actions': typeof AuthenticatedAdminAgentActionsRoute
  '/billing': typeof AuthenticatedAdminBillingRoute
  '/budget': typeof AuthenticatedAdminBudgetRoute
  '/calendar': typeof AuthenticatedAdminCalendarRoute
  '/finance': typeof AuthenticatedAdminFinanceRoute
  '/ic': typeof AuthenticatedAdminIcRoute
  '/roster': typeof AuthenticatedAdminRosterRoute
  '/tareas': typeof AuthenticatedAdminTareasRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/portal/agenda': typeof AuthenticatedPortalAgendaRoute
  '/portal/carrera': typeof AuthenticatedPortalCarreraRoute
  '/portal/chat': typeof AuthenticatedPortalChatRoute
  '/portal/contratos': typeof AuthenticatedPortalContratosRoute
  '/portal/facturacion': typeof AuthenticatedPortalFacturacionRoute
  '/portal/kpis': typeof AuthenticatedPortalKpisRoute
  '/portal/mensajes': typeof AuthenticatedPortalMensajesRoute
  '/portal/prensa': typeof AuthenticatedPortalPrensaRoute
  '/portal/propuestas': typeof AuthenticatedPortalPropuestasRoute
  '/portal/proyectos': typeof AuthenticatedPortalProyectosRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/deal-memos/$dealMemoId': typeof AuthenticatedAdminDealMemosDealMemoIdRoute
  '/deal-memos/configuracion': typeof AuthenticatedAdminDealMemosConfiguracionRoute
  '/deal-memos/lista': typeof AuthenticatedAdminDealMemosListaRoute
  '/directors/$directorId': typeof AuthenticatedAdminDirectorsDirectorIdRoute
  '/marketing/calendar': typeof AuthenticatedAdminMarketingCalendarRoute
  '/opportunities/$opportunityId': typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  '/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/production-companies/$companyId': typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  '/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/composers': typeof AuthenticatedAdminComposersIndexRoute
  '/contracts': typeof AuthenticatedAdminContractsIndexRoute
  '/deal-memos': typeof AuthenticatedAdminDealMemosIndexRoute
  '/directors': typeof AuthenticatedAdminDirectorsIndexRoute
  '/opportunities': typeof AuthenticatedAdminOpportunitiesIndexRoute
  '/peliculas-es': typeof AuthenticatedAdminPeliculasEsIndexRoute
  '/people': typeof AuthenticatedAdminPeopleIndexRoute
  '/platforms': typeof AuthenticatedAdminPlatformsIndexRoute
  '/production-companies': typeof AuthenticatedAdminProductionCompaniesIndexRoute
  '/productions': typeof AuthenticatedAdminProductionsIndexRoute
  '/providers': typeof AuthenticatedAdminProvidersIndexRoute
  '/deal-memos/plantillas/$plantillaId': typeof AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute
  '/marketing/target-accounts/$accountId': typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  '/deal-memos/plantillas': typeof AuthenticatedAdminDealMemosPlantillasIndexRoute
  '/marketing/brand': typeof AuthenticatedAdminMarketingBrandIndexRoute
  '/marketing/case-studies': typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  '/marketing/clippings': typeof AuthenticatedAdminMarketingClippingsIndexRoute
  '/marketing/decks': typeof AuthenticatedAdminMarketingDecksIndexRoute
  '/marketing/press-kits': typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  '/marketing/social': typeof AuthenticatedAdminMarketingSocialIndexRoute
  '/marketing/target-accounts': typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  '/marketing/templates': typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/vista': typeof AuthenticatedVistaRoute
  '/aprobar/$token': typeof AprobarTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/agent-actions': typeof AuthenticatedAdminAgentActionsRoute
  '/_authenticated/_admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/_admin/budget': typeof AuthenticatedAdminBudgetRoute
  '/_authenticated/_admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/_admin/deal-memos': typeof AuthenticatedAdminDealMemosRouteWithChildren
  '/_authenticated/_admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/_admin/ic': typeof AuthenticatedAdminIcRoute
  '/_authenticated/_admin/roster': typeof AuthenticatedAdminRosterRoute
  '/_authenticated/_admin/tareas': typeof AuthenticatedAdminTareasRoute
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/portal/agenda': typeof AuthenticatedPortalAgendaRoute
  '/_authenticated/portal/carrera': typeof AuthenticatedPortalCarreraRoute
  '/_authenticated/portal/chat': typeof AuthenticatedPortalChatRoute
  '/_authenticated/portal/contratos': typeof AuthenticatedPortalContratosRoute
  '/_authenticated/portal/facturacion': typeof AuthenticatedPortalFacturacionRoute
  '/_authenticated/portal/kpis': typeof AuthenticatedPortalKpisRoute
  '/_authenticated/portal/mensajes': typeof AuthenticatedPortalMensajesRoute
  '/_authenticated/portal/prensa': typeof AuthenticatedPortalPrensaRoute
  '/_authenticated/portal/propuestas': typeof AuthenticatedPortalPropuestasRoute
  '/_authenticated/portal/proyectos': typeof AuthenticatedPortalProyectosRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/_admin/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/_authenticated/_admin/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/_authenticated/_admin/contracts/$contractId': typeof AuthenticatedAdminContractsContractIdRoute
  '/_authenticated/_admin/deal-memos/$dealMemoId': typeof AuthenticatedAdminDealMemosDealMemoIdRoute
  '/_authenticated/_admin/deal-memos/configuracion': typeof AuthenticatedAdminDealMemosConfiguracionRoute
  '/_authenticated/_admin/deal-memos/lista': typeof AuthenticatedAdminDealMemosListaRoute
  '/_authenticated/_admin/directors/$directorId': typeof AuthenticatedAdminDirectorsDirectorIdRoute
  '/_authenticated/_admin/marketing/calendar': typeof AuthenticatedAdminMarketingCalendarRoute
  '/_authenticated/_admin/opportunities/$opportunityId': typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  '/_authenticated/_admin/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/_authenticated/_admin/production-companies/$companyId': typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  '/_authenticated/_admin/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/_authenticated/_admin/composers/': typeof AuthenticatedAdminComposersIndexRoute
  '/_authenticated/_admin/contracts/': typeof AuthenticatedAdminContractsIndexRoute
  '/_authenticated/_admin/deal-memos/': typeof AuthenticatedAdminDealMemosIndexRoute
  '/_authenticated/_admin/directors/': typeof AuthenticatedAdminDirectorsIndexRoute
  '/_authenticated/_admin/opportunities/': typeof AuthenticatedAdminOpportunitiesIndexRoute
  '/_authenticated/_admin/peliculas-es/': typeof AuthenticatedAdminPeliculasEsIndexRoute
  '/_authenticated/_admin/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/_authenticated/_admin/platforms/': typeof AuthenticatedAdminPlatformsIndexRoute
  '/_authenticated/_admin/production-companies/': typeof AuthenticatedAdminProductionCompaniesIndexRoute
  '/_authenticated/_admin/productions/': typeof AuthenticatedAdminProductionsIndexRoute
  '/_authenticated/_admin/providers/': typeof AuthenticatedAdminProvidersIndexRoute
  '/_authenticated/_admin/deal-memos/plantillas/$plantillaId': typeof AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute
  '/_authenticated/_admin/marketing/target-accounts/$accountId': typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  '/_authenticated/_admin/deal-memos/plantillas/': typeof AuthenticatedAdminDealMemosPlantillasIndexRoute
  '/_authenticated/_admin/marketing/brand/': typeof AuthenticatedAdminMarketingBrandIndexRoute
  '/_authenticated/_admin/marketing/case-studies/': typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  '/_authenticated/_admin/marketing/clippings/': typeof AuthenticatedAdminMarketingClippingsIndexRoute
  '/_authenticated/_admin/marketing/decks/': typeof AuthenticatedAdminMarketingDecksIndexRoute
  '/_authenticated/_admin/marketing/press-kits/': typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  '/_authenticated/_admin/marketing/social/': typeof AuthenticatedAdminMarketingSocialIndexRoute
  '/_authenticated/_admin/marketing/target-accounts/': typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  '/_authenticated/_admin/marketing/templates/': typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/me'
    | '/pending'
    | '/portal'
    | '/vista'
    | '/aprobar/$token'
    | '/agent-actions'
    | '/billing'
    | '/budget'
    | '/calendar'
    | '/deal-memos'
    | '/finance'
    | '/ic'
    | '/roster'
    | '/tareas'
    | '/users'
    | '/portal/agenda'
    | '/portal/carrera'
    | '/portal/chat'
    | '/portal/contratos'
    | '/portal/facturacion'
    | '/portal/kpis'
    | '/portal/mensajes'
    | '/portal/prensa'
    | '/portal/propuestas'
    | '/portal/proyectos'
    | '/portal/'
    | '/composers/$composerId'
    | '/composers/new'
    | '/contracts/$contractId'
    | '/deal-memos/$dealMemoId'
    | '/deal-memos/configuracion'
    | '/deal-memos/lista'
    | '/directors/$directorId'
    | '/marketing/calendar'
    | '/opportunities/$opportunityId'
    | '/people/$personId'
    | '/production-companies/$companyId'
    | '/productions/$productionId'
    | '/composers/'
    | '/contracts/'
    | '/deal-memos/'
    | '/directors/'
    | '/opportunities/'
    | '/peliculas-es/'
    | '/people/'
    | '/platforms/'
    | '/production-companies/'
    | '/productions/'
    | '/providers/'
    | '/deal-memos/plantillas/$plantillaId'
    | '/marketing/target-accounts/$accountId'
    | '/deal-memos/plantillas/'
    | '/marketing/brand/'
    | '/marketing/case-studies/'
    | '/marketing/clippings/'
    | '/marketing/decks/'
    | '/marketing/press-kits/'
    | '/marketing/social/'
    | '/marketing/target-accounts/'
    | '/marketing/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/dashboard'
    | '/me'
    | '/pending'
    | '/vista'
    | '/aprobar/$token'
    | '/agent-actions'
    | '/billing'
    | '/budget'
    | '/calendar'
    | '/finance'
    | '/ic'
    | '/roster'
    | '/tareas'
    | '/users'
    | '/portal/agenda'
    | '/portal/carrera'
    | '/portal/chat'
    | '/portal/contratos'
    | '/portal/facturacion'
    | '/portal/kpis'
    | '/portal/mensajes'
    | '/portal/prensa'
    | '/portal/propuestas'
    | '/portal/proyectos'
    | '/portal'
    | '/composers/$composerId'
    | '/composers/new'
    | '/contracts/$contractId'
    | '/deal-memos/$dealMemoId'
    | '/deal-memos/configuracion'
    | '/deal-memos/lista'
    | '/directors/$directorId'
    | '/marketing/calendar'
    | '/opportunities/$opportunityId'
    | '/people/$personId'
    | '/production-companies/$companyId'
    | '/productions/$productionId'
    | '/composers'
    | '/contracts'
    | '/deal-memos'
    | '/directors'
    | '/opportunities'
    | '/peliculas-es'
    | '/people'
    | '/platforms'
    | '/production-companies'
    | '/productions'
    | '/providers'
    | '/deal-memos/plantillas/$plantillaId'
    | '/marketing/target-accounts/$accountId'
    | '/deal-memos/plantillas'
    | '/marketing/brand'
    | '/marketing/case-studies'
    | '/marketing/clippings'
    | '/marketing/decks'
    | '/marketing/press-kits'
    | '/marketing/social'
    | '/marketing/target-accounts'
    | '/marketing/templates'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/me'
    | '/_authenticated/pending'
    | '/_authenticated/portal'
    | '/_authenticated/vista'
    | '/aprobar/$token'
    | '/_authenticated/'
    | '/_authenticated/_admin/agent-actions'
    | '/_authenticated/_admin/billing'
    | '/_authenticated/_admin/budget'
    | '/_authenticated/_admin/calendar'
    | '/_authenticated/_admin/deal-memos'
    | '/_authenticated/_admin/finance'
    | '/_authenticated/_admin/ic'
    | '/_authenticated/_admin/roster'
    | '/_authenticated/_admin/tareas'
    | '/_authenticated/_admin/users'
    | '/_authenticated/portal/agenda'
    | '/_authenticated/portal/carrera'
    | '/_authenticated/portal/chat'
    | '/_authenticated/portal/contratos'
    | '/_authenticated/portal/facturacion'
    | '/_authenticated/portal/kpis'
    | '/_authenticated/portal/mensajes'
    | '/_authenticated/portal/prensa'
    | '/_authenticated/portal/propuestas'
    | '/_authenticated/portal/proyectos'
    | '/_authenticated/portal/'
    | '/_authenticated/_admin/composers/$composerId'
    | '/_authenticated/_admin/composers/new'
    | '/_authenticated/_admin/contracts/$contractId'
    | '/_authenticated/_admin/deal-memos/$dealMemoId'
    | '/_authenticated/_admin/deal-memos/configuracion'
    | '/_authenticated/_admin/deal-memos/lista'
    | '/_authenticated/_admin/directors/$directorId'
    | '/_authenticated/_admin/marketing/calendar'
    | '/_authenticated/_admin/opportunities/$opportunityId'
    | '/_authenticated/_admin/people/$personId'
    | '/_authenticated/_admin/production-companies/$companyId'
    | '/_authenticated/_admin/productions/$productionId'
    | '/_authenticated/_admin/composers/'
    | '/_authenticated/_admin/contracts/'
    | '/_authenticated/_admin/deal-memos/'
    | '/_authenticated/_admin/directors/'
    | '/_authenticated/_admin/opportunities/'
    | '/_authenticated/_admin/peliculas-es/'
    | '/_authenticated/_admin/people/'
    | '/_authenticated/_admin/platforms/'
    | '/_authenticated/_admin/production-companies/'
    | '/_authenticated/_admin/productions/'
    | '/_authenticated/_admin/providers/'
    | '/_authenticated/_admin/deal-memos/plantillas/$plantillaId'
    | '/_authenticated/_admin/marketing/target-accounts/$accountId'
    | '/_authenticated/_admin/deal-memos/plantillas/'
    | '/_authenticated/_admin/marketing/brand/'
    | '/_authenticated/_admin/marketing/case-studies/'
    | '/_authenticated/_admin/marketing/clippings/'
    | '/_authenticated/_admin/marketing/decks/'
    | '/_authenticated/_admin/marketing/press-kits/'
    | '/_authenticated/_admin/marketing/social/'
    | '/_authenticated/_admin/marketing/target-accounts/'
    | '/_authenticated/_admin/marketing/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AprobarTokenRoute: typeof AprobarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/aprobar/$token': {
      id: '/aprobar/$token'
      path: '/aprobar/$token'
      fullPath: '/aprobar/$token'
      preLoaderRoute: typeof AprobarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vista': {
      id: '/_authenticated/vista'
      path: '/vista'
      fullPath: '/vista'
      preLoaderRoute: typeof AuthenticatedVistaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/proyectos': {
      id: '/_authenticated/portal/proyectos'
      path: '/proyectos'
      fullPath: '/portal/proyectos'
      preLoaderRoute: typeof AuthenticatedPortalProyectosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/propuestas': {
      id: '/_authenticated/portal/propuestas'
      path: '/propuestas'
      fullPath: '/portal/propuestas'
      preLoaderRoute: typeof AuthenticatedPortalPropuestasRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/prensa': {
      id: '/_authenticated/portal/prensa'
      path: '/prensa'
      fullPath: '/portal/prensa'
      preLoaderRoute: typeof AuthenticatedPortalPrensaRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/mensajes': {
      id: '/_authenticated/portal/mensajes'
      path: '/mensajes'
      fullPath: '/portal/mensajes'
      preLoaderRoute: typeof AuthenticatedPortalMensajesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/kpis': {
      id: '/_authenticated/portal/kpis'
      path: '/kpis'
      fullPath: '/portal/kpis'
      preLoaderRoute: typeof AuthenticatedPortalKpisRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/facturacion': {
      id: '/_authenticated/portal/facturacion'
      path: '/facturacion'
      fullPath: '/portal/facturacion'
      preLoaderRoute: typeof AuthenticatedPortalFacturacionRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/contratos': {
      id: '/_authenticated/portal/contratos'
      path: '/contratos'
      fullPath: '/portal/contratos'
      preLoaderRoute: typeof AuthenticatedPortalContratosRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/chat': {
      id: '/_authenticated/portal/chat'
      path: '/chat'
      fullPath: '/portal/chat'
      preLoaderRoute: typeof AuthenticatedPortalChatRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/carrera': {
      id: '/_authenticated/portal/carrera'
      path: '/carrera'
      fullPath: '/portal/carrera'
      preLoaderRoute: typeof AuthenticatedPortalCarreraRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/agenda': {
      id: '/_authenticated/portal/agenda'
      path: '/agenda'
      fullPath: '/portal/agenda'
      preLoaderRoute: typeof AuthenticatedPortalAgendaRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/tareas': {
      id: '/_authenticated/_admin/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AuthenticatedAdminTareasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/roster': {
      id: '/_authenticated/_admin/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedAdminRosterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/ic': {
      id: '/_authenticated/_admin/ic'
      path: '/ic'
      fullPath: '/ic'
      preLoaderRoute: typeof AuthenticatedAdminIcRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/finance': {
      id: '/_authenticated/_admin/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/deal-memos': {
      id: '/_authenticated/_admin/deal-memos'
      path: '/deal-memos'
      fullPath: '/deal-memos'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/calendar': {
      id: '/_authenticated/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/budget': {
      id: '/_authenticated/_admin/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedAdminBudgetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/billing': {
      id: '/_authenticated/_admin/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/agent-actions': {
      id: '/_authenticated/_admin/agent-actions'
      path: '/agent-actions'
      fullPath: '/agent-actions'
      preLoaderRoute: typeof AuthenticatedAdminAgentActionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/providers/': {
      id: '/_authenticated/_admin/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AuthenticatedAdminProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/productions/': {
      id: '/_authenticated/_admin/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof AuthenticatedAdminProductionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/production-companies/': {
      id: '/_authenticated/_admin/production-companies/'
      path: '/production-companies'
      fullPath: '/production-companies/'
      preLoaderRoute: typeof AuthenticatedAdminProductionCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/platforms/': {
      id: '/_authenticated/_admin/platforms/'
      path: '/platforms'
      fullPath: '/platforms/'
      preLoaderRoute: typeof AuthenticatedAdminPlatformsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/people/': {
      id: '/_authenticated/_admin/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedAdminPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/peliculas-es/': {
      id: '/_authenticated/_admin/peliculas-es/'
      path: '/peliculas-es'
      fullPath: '/peliculas-es/'
      preLoaderRoute: typeof AuthenticatedAdminPeliculasEsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/opportunities/': {
      id: '/_authenticated/_admin/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/directors/': {
      id: '/_authenticated/_admin/directors/'
      path: '/directors'
      fullPath: '/directors/'
      preLoaderRoute: typeof AuthenticatedAdminDirectorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/deal-memos/': {
      id: '/_authenticated/_admin/deal-memos/'
      path: '/'
      fullPath: '/deal-memos/'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDealMemosRoute
    }
    '/_authenticated/_admin/contracts/': {
      id: '/_authenticated/_admin/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedAdminContractsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/': {
      id: '/_authenticated/_admin/composers/'
      path: '/composers'
      fullPath: '/composers/'
      preLoaderRoute: typeof AuthenticatedAdminComposersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/productions/$productionId': {
      id: '/_authenticated/_admin/productions/$productionId'
      path: '/productions/$productionId'
      fullPath: '/productions/$productionId'
      preLoaderRoute: typeof AuthenticatedAdminProductionsProductionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/production-companies/$companyId': {
      id: '/_authenticated/_admin/production-companies/$companyId'
      path: '/production-companies/$companyId'
      fullPath: '/production-companies/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminProductionCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/people/$personId': {
      id: '/_authenticated/_admin/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedAdminPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/opportunities/$opportunityId': {
      id: '/_authenticated/_admin/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/calendar': {
      id: '/_authenticated/_admin/marketing/calendar'
      path: '/marketing/calendar'
      fullPath: '/marketing/calendar'
      preLoaderRoute: typeof AuthenticatedAdminMarketingCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/directors/$directorId': {
      id: '/_authenticated/_admin/directors/$directorId'
      path: '/directors/$directorId'
      fullPath: '/directors/$directorId'
      preLoaderRoute: typeof AuthenticatedAdminDirectorsDirectorIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/deal-memos/lista': {
      id: '/_authenticated/_admin/deal-memos/lista'
      path: '/lista'
      fullPath: '/deal-memos/lista'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosListaRouteImport
      parentRoute: typeof AuthenticatedAdminDealMemosRoute
    }
    '/_authenticated/_admin/deal-memos/configuracion': {
      id: '/_authenticated/_admin/deal-memos/configuracion'
      path: '/configuracion'
      fullPath: '/deal-memos/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosConfiguracionRouteImport
      parentRoute: typeof AuthenticatedAdminDealMemosRoute
    }
    '/_authenticated/_admin/deal-memos/$dealMemoId': {
      id: '/_authenticated/_admin/deal-memos/$dealMemoId'
      path: '/$dealMemoId'
      fullPath: '/deal-memos/$dealMemoId'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosDealMemoIdRouteImport
      parentRoute: typeof AuthenticatedAdminDealMemosRoute
    }
    '/_authenticated/_admin/contracts/$contractId': {
      id: '/_authenticated/_admin/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedAdminContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/new': {
      id: '/_authenticated/_admin/composers/new'
      path: '/composers/new'
      fullPath: '/composers/new'
      preLoaderRoute: typeof AuthenticatedAdminComposersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/$composerId': {
      id: '/_authenticated/_admin/composers/$composerId'
      path: '/composers/$composerId'
      fullPath: '/composers/$composerId'
      preLoaderRoute: typeof AuthenticatedAdminComposersComposerIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/templates/': {
      id: '/_authenticated/_admin/marketing/templates/'
      path: '/marketing/templates'
      fullPath: '/marketing/templates/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/target-accounts/': {
      id: '/_authenticated/_admin/marketing/target-accounts/'
      path: '/marketing/target-accounts'
      fullPath: '/marketing/target-accounts/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingTargetAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/social/': {
      id: '/_authenticated/_admin/marketing/social/'
      path: '/marketing/social'
      fullPath: '/marketing/social/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingSocialIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/press-kits/': {
      id: '/_authenticated/_admin/marketing/press-kits/'
      path: '/marketing/press-kits'
      fullPath: '/marketing/press-kits/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingPressKitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/decks/': {
      id: '/_authenticated/_admin/marketing/decks/'
      path: '/marketing/decks'
      fullPath: '/marketing/decks/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingDecksIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/clippings/': {
      id: '/_authenticated/_admin/marketing/clippings/'
      path: '/marketing/clippings'
      fullPath: '/marketing/clippings/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingClippingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/case-studies/': {
      id: '/_authenticated/_admin/marketing/case-studies/'
      path: '/marketing/case-studies'
      fullPath: '/marketing/case-studies/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingCaseStudiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/marketing/brand/': {
      id: '/_authenticated/_admin/marketing/brand/'
      path: '/marketing/brand'
      fullPath: '/marketing/brand/'
      preLoaderRoute: typeof AuthenticatedAdminMarketingBrandIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/deal-memos/plantillas/': {
      id: '/_authenticated/_admin/deal-memos/plantillas/'
      path: '/plantillas'
      fullPath: '/deal-memos/plantillas/'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosPlantillasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminDealMemosRoute
    }
    '/_authenticated/_admin/marketing/target-accounts/$accountId': {
      id: '/_authenticated/_admin/marketing/target-accounts/$accountId'
      path: '/marketing/target-accounts/$accountId'
      fullPath: '/marketing/target-accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/deal-memos/plantillas/$plantillaId': {
      id: '/_authenticated/_admin/deal-memos/plantillas/$plantillaId'
      path: '/plantillas/$plantillaId'
      fullPath: '/deal-memos/plantillas/$plantillaId'
      preLoaderRoute: typeof AuthenticatedAdminDealMemosPlantillasPlantillaIdRouteImport
      parentRoute: typeof AuthenticatedAdminDealMemosRoute
    }
  }
}

interface AuthenticatedAdminDealMemosRouteChildren {
  AuthenticatedAdminDealMemosDealMemoIdRoute: typeof AuthenticatedAdminDealMemosDealMemoIdRoute
  AuthenticatedAdminDealMemosConfiguracionRoute: typeof AuthenticatedAdminDealMemosConfiguracionRoute
  AuthenticatedAdminDealMemosListaRoute: typeof AuthenticatedAdminDealMemosListaRoute
  AuthenticatedAdminDealMemosIndexRoute: typeof AuthenticatedAdminDealMemosIndexRoute
  AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute: typeof AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute
  AuthenticatedAdminDealMemosPlantillasIndexRoute: typeof AuthenticatedAdminDealMemosPlantillasIndexRoute
}

const AuthenticatedAdminDealMemosRouteChildren: AuthenticatedAdminDealMemosRouteChildren =
  {
    AuthenticatedAdminDealMemosDealMemoIdRoute:
      AuthenticatedAdminDealMemosDealMemoIdRoute,
    AuthenticatedAdminDealMemosConfiguracionRoute:
      AuthenticatedAdminDealMemosConfiguracionRoute,
    AuthenticatedAdminDealMemosListaRoute:
      AuthenticatedAdminDealMemosListaRoute,
    AuthenticatedAdminDealMemosIndexRoute:
      AuthenticatedAdminDealMemosIndexRoute,
    AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute:
      AuthenticatedAdminDealMemosPlantillasPlantillaIdRoute,
    AuthenticatedAdminDealMemosPlantillasIndexRoute:
      AuthenticatedAdminDealMemosPlantillasIndexRoute,
  }

const AuthenticatedAdminDealMemosRouteWithChildren =
  AuthenticatedAdminDealMemosRoute._addFileChildren(
    AuthenticatedAdminDealMemosRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentActionsRoute: typeof AuthenticatedAdminAgentActionsRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminBudgetRoute: typeof AuthenticatedAdminBudgetRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminDealMemosRoute: typeof AuthenticatedAdminDealMemosRouteWithChildren
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminIcRoute: typeof AuthenticatedAdminIcRoute
  AuthenticatedAdminRosterRoute: typeof AuthenticatedAdminRosterRoute
  AuthenticatedAdminTareasRoute: typeof AuthenticatedAdminTareasRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminComposersComposerIdRoute: typeof AuthenticatedAdminComposersComposerIdRoute
  AuthenticatedAdminComposersNewRoute: typeof AuthenticatedAdminComposersNewRoute
  AuthenticatedAdminContractsContractIdRoute: typeof AuthenticatedAdminContractsContractIdRoute
  AuthenticatedAdminDirectorsDirectorIdRoute: typeof AuthenticatedAdminDirectorsDirectorIdRoute
  AuthenticatedAdminMarketingCalendarRoute: typeof AuthenticatedAdminMarketingCalendarRoute
  AuthenticatedAdminOpportunitiesOpportunityIdRoute: typeof AuthenticatedAdminOpportunitiesOpportunityIdRoute
  AuthenticatedAdminPeoplePersonIdRoute: typeof AuthenticatedAdminPeoplePersonIdRoute
  AuthenticatedAdminProductionCompaniesCompanyIdRoute: typeof AuthenticatedAdminProductionCompaniesCompanyIdRoute
  AuthenticatedAdminProductionsProductionIdRoute: typeof AuthenticatedAdminProductionsProductionIdRoute
  AuthenticatedAdminComposersIndexRoute: typeof AuthenticatedAdminComposersIndexRoute
  AuthenticatedAdminContractsIndexRoute: typeof AuthenticatedAdminContractsIndexRoute
  AuthenticatedAdminDirectorsIndexRoute: typeof AuthenticatedAdminDirectorsIndexRoute
  AuthenticatedAdminOpportunitiesIndexRoute: typeof AuthenticatedAdminOpportunitiesIndexRoute
  AuthenticatedAdminPeliculasEsIndexRoute: typeof AuthenticatedAdminPeliculasEsIndexRoute
  AuthenticatedAdminPeopleIndexRoute: typeof AuthenticatedAdminPeopleIndexRoute
  AuthenticatedAdminPlatformsIndexRoute: typeof AuthenticatedAdminPlatformsIndexRoute
  AuthenticatedAdminProductionCompaniesIndexRoute: typeof AuthenticatedAdminProductionCompaniesIndexRoute
  AuthenticatedAdminProductionsIndexRoute: typeof AuthenticatedAdminProductionsIndexRoute
  AuthenticatedAdminProvidersIndexRoute: typeof AuthenticatedAdminProvidersIndexRoute
  AuthenticatedAdminMarketingTargetAccountsAccountIdRoute: typeof AuthenticatedAdminMarketingTargetAccountsAccountIdRoute
  AuthenticatedAdminMarketingBrandIndexRoute: typeof AuthenticatedAdminMarketingBrandIndexRoute
  AuthenticatedAdminMarketingCaseStudiesIndexRoute: typeof AuthenticatedAdminMarketingCaseStudiesIndexRoute
  AuthenticatedAdminMarketingClippingsIndexRoute: typeof AuthenticatedAdminMarketingClippingsIndexRoute
  AuthenticatedAdminMarketingDecksIndexRoute: typeof AuthenticatedAdminMarketingDecksIndexRoute
  AuthenticatedAdminMarketingPressKitsIndexRoute: typeof AuthenticatedAdminMarketingPressKitsIndexRoute
  AuthenticatedAdminMarketingSocialIndexRoute: typeof AuthenticatedAdminMarketingSocialIndexRoute
  AuthenticatedAdminMarketingTargetAccountsIndexRoute: typeof AuthenticatedAdminMarketingTargetAccountsIndexRoute
  AuthenticatedAdminMarketingTemplatesIndexRoute: typeof AuthenticatedAdminMarketingTemplatesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentActionsRoute: AuthenticatedAdminAgentActionsRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminBudgetRoute: AuthenticatedAdminBudgetRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminDealMemosRoute:
    AuthenticatedAdminDealMemosRouteWithChildren,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminIcRoute: AuthenticatedAdminIcRoute,
  AuthenticatedAdminRosterRoute: AuthenticatedAdminRosterRoute,
  AuthenticatedAdminTareasRoute: AuthenticatedAdminTareasRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminComposersComposerIdRoute:
    AuthenticatedAdminComposersComposerIdRoute,
  AuthenticatedAdminComposersNewRoute: AuthenticatedAdminComposersNewRoute,
  AuthenticatedAdminContractsContractIdRoute:
    AuthenticatedAdminContractsContractIdRoute,
  AuthenticatedAdminDirectorsDirectorIdRoute:
    AuthenticatedAdminDirectorsDirectorIdRoute,
  AuthenticatedAdminMarketingCalendarRoute:
    AuthenticatedAdminMarketingCalendarRoute,
  AuthenticatedAdminOpportunitiesOpportunityIdRoute:
    AuthenticatedAdminOpportunitiesOpportunityIdRoute,
  AuthenticatedAdminPeoplePersonIdRoute: AuthenticatedAdminPeoplePersonIdRoute,
  AuthenticatedAdminProductionCompaniesCompanyIdRoute:
    AuthenticatedAdminProductionCompaniesCompanyIdRoute,
  AuthenticatedAdminProductionsProductionIdRoute:
    AuthenticatedAdminProductionsProductionIdRoute,
  AuthenticatedAdminComposersIndexRoute: AuthenticatedAdminComposersIndexRoute,
  AuthenticatedAdminContractsIndexRoute: AuthenticatedAdminContractsIndexRoute,
  AuthenticatedAdminDirectorsIndexRoute: AuthenticatedAdminDirectorsIndexRoute,
  AuthenticatedAdminOpportunitiesIndexRoute:
    AuthenticatedAdminOpportunitiesIndexRoute,
  AuthenticatedAdminPeliculasEsIndexRoute:
    AuthenticatedAdminPeliculasEsIndexRoute,
  AuthenticatedAdminPeopleIndexRoute: AuthenticatedAdminPeopleIndexRoute,
  AuthenticatedAdminPlatformsIndexRoute: AuthenticatedAdminPlatformsIndexRoute,
  AuthenticatedAdminProductionCompaniesIndexRoute:
    AuthenticatedAdminProductionCompaniesIndexRoute,
  AuthenticatedAdminProductionsIndexRoute:
    AuthenticatedAdminProductionsIndexRoute,
  AuthenticatedAdminProvidersIndexRoute: AuthenticatedAdminProvidersIndexRoute,
  AuthenticatedAdminMarketingTargetAccountsAccountIdRoute:
    AuthenticatedAdminMarketingTargetAccountsAccountIdRoute,
  AuthenticatedAdminMarketingBrandIndexRoute:
    AuthenticatedAdminMarketingBrandIndexRoute,
  AuthenticatedAdminMarketingCaseStudiesIndexRoute:
    AuthenticatedAdminMarketingCaseStudiesIndexRoute,
  AuthenticatedAdminMarketingClippingsIndexRoute:
    AuthenticatedAdminMarketingClippingsIndexRoute,
  AuthenticatedAdminMarketingDecksIndexRoute:
    AuthenticatedAdminMarketingDecksIndexRoute,
  AuthenticatedAdminMarketingPressKitsIndexRoute:
    AuthenticatedAdminMarketingPressKitsIndexRoute,
  AuthenticatedAdminMarketingSocialIndexRoute:
    AuthenticatedAdminMarketingSocialIndexRoute,
  AuthenticatedAdminMarketingTargetAccountsIndexRoute:
    AuthenticatedAdminMarketingTargetAccountsIndexRoute,
  AuthenticatedAdminMarketingTemplatesIndexRoute:
    AuthenticatedAdminMarketingTemplatesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAgendaRoute: typeof AuthenticatedPortalAgendaRoute
  AuthenticatedPortalCarreraRoute: typeof AuthenticatedPortalCarreraRoute
  AuthenticatedPortalChatRoute: typeof AuthenticatedPortalChatRoute
  AuthenticatedPortalContratosRoute: typeof AuthenticatedPortalContratosRoute
  AuthenticatedPortalFacturacionRoute: typeof AuthenticatedPortalFacturacionRoute
  AuthenticatedPortalKpisRoute: typeof AuthenticatedPortalKpisRoute
  AuthenticatedPortalMensajesRoute: typeof AuthenticatedPortalMensajesRoute
  AuthenticatedPortalPrensaRoute: typeof AuthenticatedPortalPrensaRoute
  AuthenticatedPortalPropuestasRoute: typeof AuthenticatedPortalPropuestasRoute
  AuthenticatedPortalProyectosRoute: typeof AuthenticatedPortalProyectosRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAgendaRoute: AuthenticatedPortalAgendaRoute,
  AuthenticatedPortalCarreraRoute: AuthenticatedPortalCarreraRoute,
  AuthenticatedPortalChatRoute: AuthenticatedPortalChatRoute,
  AuthenticatedPortalContratosRoute: AuthenticatedPortalContratosRoute,
  AuthenticatedPortalFacturacionRoute: AuthenticatedPortalFacturacionRoute,
  AuthenticatedPortalKpisRoute: AuthenticatedPortalKpisRoute,
  AuthenticatedPortalMensajesRoute: AuthenticatedPortalMensajesRoute,
  AuthenticatedPortalPrensaRoute: AuthenticatedPortalPrensaRoute,
  AuthenticatedPortalPropuestasRoute: AuthenticatedPortalPropuestasRoute,
  AuthenticatedPortalProyectosRoute: AuthenticatedPortalProyectosRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedVistaRoute: typeof AuthenticatedVistaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedVistaRoute: AuthenticatedVistaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AprobarTokenRoute: AprobarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
