/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminRosterRouteImport } from './routes/_authenticated/_admin/roster'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/_admin/calendar'
import { Route as AuthenticatedAdminProductionsIndexRouteImport } from './routes/_authenticated/_admin/productions.index'
import { Route as AuthenticatedAdminPeopleIndexRouteImport } from './routes/_authenticated/_admin/people.index'
import { Route as AuthenticatedAdminComposersIndexRouteImport } from './routes/_authenticated/_admin/composers.index'
import { Route as AuthenticatedAdminProductionsProductionIdRouteImport } from './routes/_authenticated/_admin/productions.$productionId'
import { Route as AuthenticatedAdminPeoplePersonIdRouteImport } from './routes/_authenticated/_admin/people.$personId'
import { Route as AuthenticatedAdminComposersNewRouteImport } from './routes/_authenticated/_admin/composers.new'
import { Route as AuthenticatedAdminComposersComposerIdRouteImport } from './routes/_authenticated/_admin/composers.$composerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRosterRoute =
  AuthenticatedAdminRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionsIndexRoute =
  AuthenticatedAdminProductionsIndexRouteImport.update({
    id: '/productions/',
    path: '/productions/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleIndexRoute =
  AuthenticatedAdminPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersIndexRoute =
  AuthenticatedAdminComposersIndexRouteImport.update({
    id: '/composers/',
    path: '/composers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionsProductionIdRoute =
  AuthenticatedAdminProductionsProductionIdRouteImport.update({
    id: '/productions/$productionId',
    path: '/productions/$productionId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeoplePersonIdRoute =
  AuthenticatedAdminPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersNewRoute =
  AuthenticatedAdminComposersNewRouteImport.update({
    id: '/composers/new',
    path: '/composers/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComposersComposerIdRoute =
  AuthenticatedAdminComposersComposerIdRouteImport.update({
    id: '/composers/$composerId',
    path: '/composers/$composerId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/calendar': typeof AuthenticatedAdminCalendarRoute
  '/roster': typeof AuthenticatedAdminRosterRoute
  '/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/composers/': typeof AuthenticatedAdminComposersIndexRoute
  '/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/productions/': typeof AuthenticatedAdminProductionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/me': typeof AuthenticatedMeRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/calendar': typeof AuthenticatedAdminCalendarRoute
  '/roster': typeof AuthenticatedAdminRosterRoute
  '/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/composers': typeof AuthenticatedAdminComposersIndexRoute
  '/people': typeof AuthenticatedAdminPeopleIndexRoute
  '/productions': typeof AuthenticatedAdminProductionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/_admin/roster': typeof AuthenticatedAdminRosterRoute
  '/_authenticated/_admin/composers/$composerId': typeof AuthenticatedAdminComposersComposerIdRoute
  '/_authenticated/_admin/composers/new': typeof AuthenticatedAdminComposersNewRoute
  '/_authenticated/_admin/people/$personId': typeof AuthenticatedAdminPeoplePersonIdRoute
  '/_authenticated/_admin/productions/$productionId': typeof AuthenticatedAdminProductionsProductionIdRoute
  '/_authenticated/_admin/composers/': typeof AuthenticatedAdminComposersIndexRoute
  '/_authenticated/_admin/people/': typeof AuthenticatedAdminPeopleIndexRoute
  '/_authenticated/_admin/productions/': typeof AuthenticatedAdminProductionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/me'
    | '/portal'
    | '/calendar'
    | '/roster'
    | '/composers/$composerId'
    | '/composers/new'
    | '/people/$personId'
    | '/productions/$productionId'
    | '/composers/'
    | '/people/'
    | '/productions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/dashboard'
    | '/me'
    | '/portal'
    | '/calendar'
    | '/roster'
    | '/composers/$composerId'
    | '/composers/new'
    | '/people/$personId'
    | '/productions/$productionId'
    | '/composers'
    | '/people'
    | '/productions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/me'
    | '/_authenticated/portal'
    | '/_authenticated/'
    | '/_authenticated/_admin/calendar'
    | '/_authenticated/_admin/roster'
    | '/_authenticated/_admin/composers/$composerId'
    | '/_authenticated/_admin/composers/new'
    | '/_authenticated/_admin/people/$personId'
    | '/_authenticated/_admin/productions/$productionId'
    | '/_authenticated/_admin/composers/'
    | '/_authenticated/_admin/people/'
    | '/_authenticated/_admin/productions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/roster': {
      id: '/_authenticated/_admin/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedAdminRosterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/calendar': {
      id: '/_authenticated/_admin/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/productions/': {
      id: '/_authenticated/_admin/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof AuthenticatedAdminProductionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/people/': {
      id: '/_authenticated/_admin/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedAdminPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/': {
      id: '/_authenticated/_admin/composers/'
      path: '/composers'
      fullPath: '/composers/'
      preLoaderRoute: typeof AuthenticatedAdminComposersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/productions/$productionId': {
      id: '/_authenticated/_admin/productions/$productionId'
      path: '/productions/$productionId'
      fullPath: '/productions/$productionId'
      preLoaderRoute: typeof AuthenticatedAdminProductionsProductionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/people/$personId': {
      id: '/_authenticated/_admin/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedAdminPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/new': {
      id: '/_authenticated/_admin/composers/new'
      path: '/composers/new'
      fullPath: '/composers/new'
      preLoaderRoute: typeof AuthenticatedAdminComposersNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/composers/$composerId': {
      id: '/_authenticated/_admin/composers/$composerId'
      path: '/composers/$composerId'
      fullPath: '/composers/$composerId'
      preLoaderRoute: typeof AuthenticatedAdminComposersComposerIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminRosterRoute: typeof AuthenticatedAdminRosterRoute
  AuthenticatedAdminComposersComposerIdRoute: typeof AuthenticatedAdminComposersComposerIdRoute
  AuthenticatedAdminComposersNewRoute: typeof AuthenticatedAdminComposersNewRoute
  AuthenticatedAdminPeoplePersonIdRoute: typeof AuthenticatedAdminPeoplePersonIdRoute
  AuthenticatedAdminProductionsProductionIdRoute: typeof AuthenticatedAdminProductionsProductionIdRoute
  AuthenticatedAdminComposersIndexRoute: typeof AuthenticatedAdminComposersIndexRoute
  AuthenticatedAdminPeopleIndexRoute: typeof AuthenticatedAdminPeopleIndexRoute
  AuthenticatedAdminProductionsIndexRoute: typeof AuthenticatedAdminProductionsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminRosterRoute: AuthenticatedAdminRosterRoute,
  AuthenticatedAdminComposersComposerIdRoute:
    AuthenticatedAdminComposersComposerIdRoute,
  AuthenticatedAdminComposersNewRoute: AuthenticatedAdminComposersNewRoute,
  AuthenticatedAdminPeoplePersonIdRoute: AuthenticatedAdminPeoplePersonIdRoute,
  AuthenticatedAdminProductionsProductionIdRoute:
    AuthenticatedAdminProductionsProductionIdRoute,
  AuthenticatedAdminComposersIndexRoute: AuthenticatedAdminComposersIndexRoute,
  AuthenticatedAdminPeopleIndexRoute: AuthenticatedAdminPeopleIndexRoute,
  AuthenticatedAdminProductionsIndexRoute:
    AuthenticatedAdminProductionsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
